@extends('admin.master.master')
@section('title','Kitchen Requests')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Kitchen Requests</h1><p class="text-muted mb-0">Request Food items and Direct Ingredients separately or together in one request. Stock changes only when Store posts an issue transfer.</p></div>@can('inventory-kitchen-request-create')<a href="{{ route('inventory.kitchen-requests.create') }}" class="progga-btn progga-btn-primary"><i class="bi bi-plus-lg"></i> New Request</a>@endcan</div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="progga-card mb-4 inventory-filter-card"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-lg-2"><label class="progga-form-label">Type</label><select name="request_type" class="progga-form-control"><option value="">All types</option>@foreach($types as $type)<option value="{{ $type }}" @selected(request('request_type')===$type)>{{ match($type){'FOOD'=>'Food-wise','INGREDIENT'=>'Ingredient-wise','MIXED'=>'Food + Direct',default=>$type} }}</option>@endforeach</select></div><div class="col-lg-2"><label class="progga-form-label">Status</label><select name="status" class="progga-form-control"><option value="">All status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',$status) }}</option>@endforeach</select></div><div class="col-lg-2"><label class="progga-form-label">From</label><input type="text" name="date_from" value="{{ request('date_from') }}" class="progga-form-control progga-datepicker"></div><div class="col-lg-2"><label class="progga-form-label">To</label><input type="text" name="date_to" value="{{ request('date_to') }}" class="progga-form-control progga-datepicker"></div><div class="col-lg-auto"><button class="progga-btn progga-btn-secondary">Apply Filter</button></div><div class="col-lg-auto"><a href="{{ route('inventory.kitchen-requests.index') }}" class="progga-btn progga-btn-light">Clear</a></div></form></div></div>
    <div class="progga-card">
        <div class="progga-card-header inventory-list-toolbar"><div class="inventory-result-copy"><span class="fw-semibold">Request List</span><small class="text-muted" id="inventoryResultCount">{{ $requests->total() }} {{ $requests->total() === 1 ? 'record' : 'records' }}</small></div><div class="inventory-search-wrap"><i class="bi bi-search inventory-search-icon"></i><input type="search" id="inventorySearch" class="progga-form-control inventory-search-input" value="{{ request('search') }}" placeholder="Search request number..." autocomplete="off"><button type="button" id="inventorySearchClear" class="inventory-search-clear"><i class="bi bi-x-lg"></i></button></div></div>
        <div id="inventoryListContent"><div class="progga-table-wrapper" style="border:none;border-radius:0;"><table class="progga-table"><thead><tr><th style="width:70px;">SL</th>@if(($allBranchesSelected ?? false))<th>Branch</th>@endif<th>Request</th><th>Type</th><th>Date</th><th>Requirement</th><th>Transfers</th><th>Status</th><th style="width:130px;">Actions</th></tr></thead><tbody>
        @forelse($requests as $item)@php $badge=match($item->status){'DRAFT'=>'neutral','SUBMITTED'=>'info','PARTIALLY_ISSUED'=>'warning','FULLY_ISSUED'=>'success','CLOSED'=>'primary','CANCELLED'=>'danger',default=>'neutral'}; @endphp<tr><td>{{ ($requests->firstItem() ?? 1)+$loop->index }}</td>@if(($allBranchesSelected ?? false))<td>{{ $item->branch?->name }}</td>@endif<td><a href="{{ route('inventory.kitchen-requests.show',$item) }}"><strong>{{ $item->request_no }}</strong></a><br><small class="text-muted">By {{ $item->requester?->name ?: '—' }}</small></td><td>{{ match($item->request_type){'FOOD'=>'Food-wise','INGREDIENT'=>'Ingredient-wise','MIXED'=>'Food + Direct',default=>$item->request_type} }}</td><td>{{ optional($item->request_date)->format('d M Y') }}</td><td>{{ match($item->request_type){'FOOD'=>$item->food_items_count.' food item(s)','INGREDIENT'=>$item->ingredient_items_count.' ingredient(s)','MIXED'=>$item->food_items_count.' food + '.$item->direct_ingredient_items_count.' direct ingredient(s)',default=>$item->ingredient_items_count.' ingredient(s)'} }}</td><td>{{ $item->transfers_count }}</td><td><span class="progga-badge progga-badge-{{ $badge }}">{{ str_replace('_',' ',$item->status) }}</span></td><td><div class="progga-table-actions"><a href="{{ route('inventory.kitchen-requests.show',$item) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="View"><i class="bi bi-eye"></i></a>@if($item->isEditable()) @can('inventory-kitchen-request-create')<a href="{{ route('inventory.kitchen-requests.edit',$item) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Edit"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('inventory.kitchen-requests.destroy',$item) }}" class="d-inline">@csrf @method('DELETE')<button type="button" class="progga-btn progga-btn-danger progga-btn-icon progga-btn-sm" title="Delete" data-delete-name="{{ $item->request_no }}" onclick="inventoryConfirmDelete(this)"><i class="bi bi-trash"></i></button></form>@endcan @endif</div></td></tr>@empty<tr><td colspan="{{ ($allBranchesSelected ?? false) ? 9 : 8 }}" class="text-center text-muted py-5">No kitchen requests found.</td></tr>@endforelse
        </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$requests,'label'=>'requests'])</div>
    </div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.kitchen-requests.index')])
@endsection
