<div class="modal fade hr-modal" id="shiftModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="shiftForm">@csrf
<div class="modal-header"><div><h5 class="modal-title" id="shiftModalTitle">Add Shift</h5><div style="font-size:11px;opacity:.75">Use 24-hour time internally; the screen shows a friendly time picker.</div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="row g-3">
<div class="col-md-6"><label class="progga-form-label">Shift Name <span class="progga-required">*</span></label><input name="name" id="shiftName" class="progga-form-control"><div class="shift-error text-danger" data-error="name"></div></div>
<div class="col-md-3"><label class="progga-form-label">Code</label><input name="code" id="shiftCode" class="progga-form-control" placeholder="MORNING"><div class="shift-error text-danger" data-error="code"></div></div>
<div class="col-md-3"><label class="progga-form-label">Sort Order</label><input type="number" min="0" name="sort_order" id="shiftSort" class="progga-form-control" value="0"></div>
<div class="col-md-6"><label class="progga-form-label">Start Time <span class="progga-required">*</span></label><input name="start_time" id="shiftStart" class="progga-form-control shift-time"><div class="shift-error text-danger" data-error="start_time"></div></div>
<div class="col-md-6"><label class="progga-form-label">End Time <span class="progga-required">*</span></label><input name="end_time" id="shiftEnd" class="progga-form-control shift-time"><div class="shift-error text-danger" data-error="end_time"></div></div>
<div class="col-md-4"><label class="progga-form-label">Break Minutes</label><input type="number" min="0" max="720" name="break_minutes" id="shiftBreak" class="progga-form-control" value="0"></div>
<div class="col-md-4"><label class="progga-form-label">Grace Minutes</label><input type="number" min="0" max="180" name="grace_minutes" id="shiftGrace" class="progga-form-control" value="0"></div>
<div class="col-md-4"><div class="p-3" style="border:1px solid var(--progga-border-light);border-radius:12px"><label class="progga-toggle"><input type="checkbox" id="shiftOvernight"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">Overnight Shift</span></label></div></div>
<div class="col-md-4"><div class="p-3" style="border:1px solid var(--progga-border-light);border-radius:12px"><label class="progga-toggle"><input type="checkbox" id="shiftStatus" checked><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">Active</span></label></div></div>
<div class="col-12"><label class="progga-form-label">Notes</label><textarea name="notes" id="shiftNotes" class="progga-form-control" rows="3"></textarea></div>
</div></div><div class="modal-footer"><button type="button" class="progga-btn progga-btn-outline" data-bs-dismiss="modal">Cancel</button><button type="submit" class="progga-btn progga-btn-primary" id="shiftSaveBtn"><i class="bi bi-check-lg"></i> <span id="shiftSaveText">Save Shift</span></button></div>
</form></div></div></div>
