<div class="progga-table-wrapper" style="border:0;border-radius:0"><table class="progga-table"><thead><tr><th>#</th><th>Employee</th><th>Leave Type</th><th>Period</th><th>Days</th><th>Reason</th><th>Status</th><th>Approved By</th><th style="width:150px">Actions</th></tr></thead><tbody>
@forelse($leaves as $index=>$leave)
@php $payload=base64_encode(json_encode(['employee_id'=>$leave->employee_id,'leave_type_id'=>$leave->leave_type_id,'from_date'=>$leave->from_date->format('Y-m-d'),'to_date'=>$leave->to_date->format('Y-m-d'),'reason'=>$leave->reason]));$badge=['pending'=>'warning','approved'=>'success','rejected'=>'danger','cancelled'=>'neutral'][$leave->status]??'neutral'; @endphp
<tr><td>{{ $leaves->firstItem()+$index }}</td><td><div class="hr-person"><img class="hr-table-avatar" src="{{ $leave->employee?->image ? asset($leave->employee->image) : 'https://ui-avatars.com/api/?name='.urlencode($leave->employee?->name ?? 'Employee').'&background=21352a&color=d5aa65&size=80' }}"><div><div class="hr-person-name">{{ $leave->employee?->name }}</div><div class="hr-person-meta">{{ $leave->employee?->employee_code }} · {{ $leave->employee?->department?->name }}</div></div></div></td>
<td><span class="hr-badge hr-badge-primary" style="border-left:3px solid {{ $leave->leaveType?->color ?: '#21352a' }}">{{ $leave->leaveType?->name }}</span><div class="hr-person-meta mt-1">{{ $leave->is_paid ? 'Paid' : 'Unpaid' }}</div></td>
<td><div style="font-weight:700">{{ $leave->from_date->format('d-m-Y') }}</div><div class="hr-person-meta">to {{ $leave->to_date->format('d-m-Y') }}</div></td><td><strong>{{ rtrim(rtrim(number_format((float)$leave->total_days,2),'0'),'.') }}</strong></td><td><div style="max-width:220px;white-space:normal">{{ \Illuminate\Support\Str::limit($leave->reason,75) }}</div>@if($leave->attachment)<a href="{{ asset($leave->attachment) }}" target="_blank" class="hr-muted"><i class="bi bi-paperclip"></i> Attachment</a>@endif</td>
<td><span class="hr-badge hr-badge-{{ $badge }}">{{ $leave->status }}</span></td><td><div>{{ $leave->approvedBy?->name ?? '—' }}</div><div class="hr-person-meta">{{ $leave->approved_at?->format('d-m-Y h:i A') }}</div></td>
<td><div class="progga-table-actions flex-wrap">@if($leave->status==='pending')@can('leave-management-edit')<button class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm leave-edit-btn" data-id="{{ $leave->id }}" data-payload="{{ $payload }}" title="Edit"><i class="bi bi-pencil"></i></button>@endcan @can('leave-management-approve')<button class="progga-btn progga-btn-primary progga-btn-icon progga-btn-sm leave-decision-btn" data-id="{{ $leave->id }}" data-decision="approved" title="Approve"><i class="bi bi-check-lg"></i></button><button class="progga-btn progga-btn-danger progga-btn-icon progga-btn-sm leave-decision-btn" data-id="{{ $leave->id }}" data-decision="rejected" title="Reject"><i class="bi bi-x-lg"></i></button>@endcan @endif @if(in_array($leave->status,['pending','approved']))@can('leave-management-edit')<button class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm leave-cancel-btn" data-id="{{ $leave->id }}" title="Cancel"><i class="bi bi-slash-circle"></i></button>@endcan @endif @if(in_array($leave->status,['pending','rejected','cancelled']))@can('leave-management-delete')<button class="progga-btn progga-btn-danger progga-btn-icon progga-btn-sm leave-delete-btn" data-id="{{ $leave->id }}" title="Delete"><i class="bi bi-trash"></i></button>@endcan @endif</div></td>
</tr>@empty<tr><td colspan="9"><div class="hr-empty"><i class="bi bi-calendar2-check"></i>No leave requests found.</div></td></tr>@endforelse
</tbody></table></div>
@include('admin.partials.custom_pagination',['paginator'=>$leaves])
