@extends('admin.master.master')
@section('title','Inventory Exceptions')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Inventory Exception Queue</h1><p class="text-muted mb-0">Operational inconsistencies such as negative Kitchen stock or missing recipe configuration are reconciled here.</p></div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="progga-card mb-4 inventory-filter-card"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-md-3"><label class="progga-form-label">Status</label><select name="status" class="progga-form-control"><option value="">All statuses</option><option value="OPEN" @selected(request('status')==='OPEN')>Open</option><option value="RESOLVED" @selected(request('status')==='RESOLVED')>Resolved</option></select></div><div class="col-md-5"><label class="progga-form-label">Type</label><select name="exception_type" class="progga-form-control"><option value="">All types</option>@foreach($types as $type)<option value="{{ $type }}" @selected(request('exception_type')===$type)>{{ str_replace('_',' ',$type) }}</option>@endforeach</select></div><div class="col-md-auto"><button class="progga-btn progga-btn-secondary">Apply Filter</button></div><div class="col-md-auto"><a href="{{ route('inventory.exceptions.index') }}" class="progga-btn progga-btn-light">Clear</a></div></form></div></div>
    <div class="progga-card">
        <div class="progga-card-header inventory-list-toolbar"><div class="inventory-result-copy"><span class="fw-semibold">Exception List</span><small class="text-muted" id="inventoryResultCount">{{ $exceptions->total() }} {{ $exceptions->total() === 1 ? 'record' : 'records' }}</small></div><div class="inventory-search-wrap"><i class="bi bi-search inventory-search-icon"></i><input type="search" id="inventorySearch" class="progga-form-control inventory-search-input" value="{{ request('search') }}" placeholder="Search ingredient, location or type..." autocomplete="off"><button type="button" id="inventorySearchClear" class="inventory-search-clear"><i class="bi bi-x-lg"></i></button></div></div>
        <div id="inventoryListContent"><div class="progga-table-wrapper" style="border:none;border-radius:0;"><table class="progga-table"><thead><tr><th style="width:70px;">SL</th><th>Status</th><th>Type</th><th>Branch</th><th>Ingredient</th><th>Location</th><th>Shortage</th><th>Detected</th><th style="width:70px;">Actions</th></tr></thead><tbody>
        @forelse($exceptions as $e)<tr><td>{{ ($exceptions->firstItem() ?? 1)+$loop->index }}</td><td><span class="progga-badge progga-badge-{{ $e->status==='OPEN'?'danger':'success' }}">{{ $e->status }}</span></td><td>{{ str_replace('_',' ',$e->exception_type) }}</td><td>{{ $e->branch?->name }}</td><td>{{ $e->ingredient?->name ?: '—' }}</td><td>{{ $e->location?->name ?: '—' }}</td><td>@if($e->ingredient){{ rtrim(rtrim((string)$e->shortage_base,'0'),'.') }} {{ $e->ingredient?->baseUnit?->symbol }}@else—@endif</td><td>{{ $e->detected_at?->format('d M Y h:i A') }}</td><td><div class="progga-table-actions"><a href="{{ route('inventory.exceptions.show',$e) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Review"><i class="bi bi-eye"></i></a></div></td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-5">No inventory exceptions found.</td></tr>@endforelse
        </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$exceptions,'label'=>'exceptions'])</div>
    </div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.exceptions.index')])
@endsection
