@extends('admin.master.master')
@section('title','Inventory Exception')
@section('body')
<main class="progga-content"><div class="progga-page-header"><div><h1 class="progga-page-title">{{ str_replace('_',' ',$exception->exception_type) }}</h1><p class="text-muted mb-0">{{ $exception->branch?->name }} · detected {{ $exception->detected_at?->format('d M Y h:i A') }}</p></div><a href="{{ route('inventory.exceptions.index') }}" class="progga-btn progga-btn-outline">Back</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="progga-card mb-4"><div class="p-4"><div class="row g-3"><div class="col-md-3"><small class="text-muted">Status</small><div><span class="badge {{ $exception->status==='OPEN'?'bg-danger':'bg-success' }}">{{ $exception->status }}</span></div></div><div class="col-md-3"><small class="text-muted">Ingredient</small><div>{{ $exception->ingredient?->name ?: '—' }}</div></div><div class="col-md-3"><small class="text-muted">Location</small><div>{{ $exception->location?->name ?: '—' }}</div></div><div class="col-md-3"><small class="text-muted">Shortage</small><div>@if($exception->ingredient){{ rtrim(rtrim((string)$exception->shortage_base,'0'),'.') }} {{ $exception->ingredient?->baseUnit?->symbol }}@else—@endif</div></div>@if($consumption)<div class="col-12"><small class="text-muted">Consumption Reference</small><div><a href="{{ route('inventory.consumptions.show',$consumption) }}">Order #{{ $consumption->order_id }} inventory consumption</a></div></div>@endif</div></div></div>
@if($exception->exception_type==='NEGATIVE_KITCHEN_STOCK')<div class="alert alert-warning">Order completion was intentionally not blocked by the shortage. Reconcile the physical stock and, if correction is required, post a Physical Stock Adjustment rather than editing the balance directly.</div>@endif
@if($exception->status==='OPEN')@can('inventory-adjustment-post')<div class="progga-card"><div class="p-4"><div class="d-flex justify-content-between align-items-start gap-3"><div><strong>Resolve exception</strong><p class="text-muted mb-0">Resolution records acknowledgement only; it does not change stock.</p></div><a href="{{ route('inventory.adjustments.create') }}" class="progga-btn progga-btn-secondary">Open Physical Adjustment</a></div><form method="POST" action="{{ route('inventory.exceptions.resolve',$exception) }}" class="mt-3">@csrf<label class="progga-form-label">Resolution Note</label><textarea name="resolution_note" rows="3" class="progga-form-control" required>{{ old('resolution_note') }}</textarea><div class="mt-3 text-end"><button class="progga-btn progga-btn-primary">Mark Resolved</button></div></form></div></div>@endcan @else<div class="progga-card"><div class="p-4"><strong>Resolved:</strong> {{ $exception->resolved_at?->format('d M Y h:i A') }} by {{ $exception->resolver?->name ?: '—' }}<br><strong>Note:</strong> {{ $exception->resolution_note ?: '—' }}</div></div>@endif
</main>
@endsection
