@extends('admin.master.master')
@section('title', 'Shifts & Duty Roster — ' . $restaurantSettingName)
@section('css')
@include('admin.hr.shared.styles')
<style>
.hr-shift-tabs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-bottom:18px}.hr-shift-tab{border:1px solid rgba(33,53,42,.12);border-radius:13px;background:#fff;padding:14px 16px;display:flex;align-items:center;gap:12px;text-align:left;box-shadow:0 5px 16px rgba(33,53,42,.05);color:var(--progga-text)}.hr-shift-tab i{width:38px;height:38px;border-radius:10px;background:rgba(33,53,42,.08);display:flex;align-items:center;justify-content:center;color:var(--progga-primary);font-size:17px}.hr-shift-tab.active{background:linear-gradient(135deg,var(--progga-primary),#355b46);color:#fff}.hr-shift-tab.active i{background:rgba(255,255,255,.14);color:#fff}.hr-shift-tab-title{font-size:13px;font-weight:900}.hr-shift-tab-sub{font-size:10px;opacity:.7;margin-top:2px}.hr-shift-panel{display:none}.hr-shift-panel.active{display:block}.roster-table th,.roster-table td{min-width:130px;text-align:center}.roster-table th:first-child,.roster-table td:first-child{min-width:220px;text-align:left;position:sticky;left:0;background:#fff;z-index:2}.roster-table thead th:first-child{background:#f5f6f5;z-index:3}.roster-select{min-width:120px;padding:7px 28px 7px 8px}.roster-day{font-size:10px;color:var(--progga-text-muted)}@media(max-width:575px){.hr-shift-tabs{grid-template-columns:1fr}}
</style>
@endsection
@section('body')
<main class="progga-content"><div class="hr-shell">
<div class="progga-page-header"><div><h1 class="progga-page-title">Shifts & Duty Roster</h1><div class="progga-breadcrumb"><a href="{{ route('home') }}" class="progga-breadcrumb-item">Dashboard</a><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">Human Resources</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item active">Shifts</span></div></div></div>
<div class="hr-stat-grid">
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-clock"></i></div><div><div class="hr-stat-value">{{ $totalShifts }}</div><div class="hr-stat-label">Total Shifts</div></div></div>
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-clock-fill"></i></div><div><div class="hr-stat-value">{{ $activeShifts }}</div><div class="hr-stat-label">Active Shifts</div></div></div>
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-calendar-week"></i></div><div><div class="hr-stat-value">{{ $scheduledToday }}</div><div class="hr-stat-label">Scheduled Today</div></div></div>
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-moon-stars"></i></div><div><div class="hr-stat-value">{{ $offToday }}</div><div class="hr-stat-label">Off Today</div></div></div>
</div>
<div class="hr-shift-tabs"><button class="hr-shift-tab active" data-panel="shiftSetupPanel"><i class="bi bi-clock-history"></i><div><div class="hr-shift-tab-title">Shift Setup</div><div class="hr-shift-tab-sub">Create and manage working shifts</div></div></button><button class="hr-shift-tab" data-panel="dutyRosterPanel"><i class="bi bi-calendar3"></i><div><div class="hr-shift-tab-title">Weekly Duty Roster</div><div class="hr-shift-tab-sub">Assign shifts employee-wise</div></div></button></div>

<div class="hr-shift-panel active" id="shiftSetupPanel">
<div class="hr-card mb-3"><div class="hr-card-header"><div><div class="hr-card-title">Shift Setup</div><div class="hr-card-subtitle">Configure start time, end time, break and grace period.</div></div>@can('shift-create')<button class="progga-btn progga-btn-primary" id="addShiftBtn"><i class="bi bi-plus-lg"></i> Add Shift</button>@endcan</div><div class="hr-card-body"><div class="hr-filter-grid"><div class="hr-search"><i class="bi bi-search"></i><input id="shiftSearch" class="progga-form-control" placeholder="Search shift name or code"></div><select id="shiftStatusFilter" class="shift-select2"><option value="">All Status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><div></div><div></div><button id="shiftReset" class="progga-btn progga-btn-outline"><i class="bi bi-arrow-counterclockwise"></i> Reset</button></div></div></div>
<div class="hr-card" id="shiftTableContainer"><div class="hr-empty"><div class="spinner-border spinner-border-sm"></div><div class="mt-2">Loading shifts...</div></div></div>
</div>

<div class="hr-shift-panel" id="dutyRosterPanel">
<div class="hr-card mb-3"><div class="hr-card-header"><div><div class="hr-card-title">Weekly Duty Roster</div><div class="hr-card-subtitle">Blank means no roster entry. Select OFF for a weekly off day.</div></div><div class="d-flex gap-2 flex-wrap">@can('shift-roster-manage')<button class="progga-btn progga-btn-outline" id="copyRosterBtn"><i class="bi bi-files"></i> Copy Previous Week</button><button class="progga-btn progga-btn-primary" id="saveRosterBtn"><i class="bi bi-check2-circle"></i> Save Visible Roster</button>@endcan</div></div><div class="hr-card-body"><div class="hr-filter-grid">
<div class="hr-search"><i class="bi bi-search"></i><input id="rosterSearch" class="progga-form-control" placeholder="Search employee"></div>
<div><label class="progga-form-label">Week Starting</label><input id="rosterWeekStart" class="progga-form-control" value="{{ $weekStart }}"></div>
<div><label class="progga-form-label">Department</label><select id="rosterDepartment" class="roster-filter-select2"><option value="">All Departments</option>@foreach($departments as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div>
<div></div><button id="rosterReset" class="progga-btn progga-btn-outline"><i class="bi bi-arrow-counterclockwise"></i> Reset</button>
</div></div></div>
<div class="hr-card" id="rosterTableContainer"><div class="hr-empty"><div class="spinner-border spinner-border-sm"></div><div class="mt-2">Loading roster...</div></div></div>
</div>
</div></main>
@include('admin.hr.shifts.modals.form')
@endsection
@section('script')
@include('admin.hr.shared.plugins')
<script>
$(function(){
 let shiftPage=1,rosterPage=1,shiftTimer=null,rosterTimer=null,editShiftId=null;const modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('shiftModal'));
 HrUi.initSelect2('.shift-select2,.roster-filter-select2');
 const weekPicker=flatpickr('#rosterWeekStart',{dateFormat:'Y-m-d',altInput:true,altFormat:'d-m-Y',allowInput:true,onChange:()=>loadRoster(1)});
 flatpickr('.shift-time',{enableTime:true,noCalendar:true,dateFormat:'H:i',time_24hr:false,allowInput:true});
 function cv(id){return HrUi.selectValue(id)} function setSelect(id,v){HrUi.setSelectValue(id,v);}
 $('.hr-shift-tab').on('click',function(){$('.hr-shift-tab').removeClass('active');$(this).addClass('active');$('.hr-shift-panel').removeClass('active');$('#'+$(this).data('panel')).addClass('active');if($(this).data('panel')==='dutyRosterPanel')loadRoster(rosterPage)});
 function loadShifts(p=1){shiftPage=p;$('#shiftTableContainer').addClass('hr-table-loading');$.get("{{ route('hr.shifts.table') }}",{page:p,search:$('#shiftSearch').val(),status:cv('shiftStatusFilter')}).done(function(html){const container=$('#shiftTableContainer');container.html(html);HrUi.initSelect2(container);}).fail(()=>Swal.fire('Error','Failed to load shifts.','error')).always(()=>$('#shiftTableContainer').removeClass('hr-table-loading'));}
 $('#shiftSearch').on('input',()=>{clearTimeout(shiftTimer);shiftTimer=setTimeout(()=>loadShifts(1),350)});$('#shiftStatusFilter').on('change',()=>loadShifts(1));$('#shiftReset').on('click',function(){$('#shiftSearch').val('');HrUi.resetSelect('shiftStatusFilter');loadShifts(1)});$(document).on('click','#shiftTableContainer .report-page-link:not(.disabled)',function(e){e.preventDefault();const u=new URL(this.href);loadShifts(u.searchParams.get('page')||1)});
 function resetShiftForm(){editShiftId=null;$('#shiftForm')[0].reset();$('#shiftModalTitle').text('Add Shift');$('#shiftSaveText').text('Save Shift');$('#shiftStatus').prop('checked',true);$('#shiftOvernight').prop('checked',false);$('#shiftBreak').val(0);$('#shiftGrace').val(0);$('#shiftSort').val(0);$('.shift-error').text('');}
 $('#addShiftBtn').on('click',()=>{resetShiftForm();modal.show()});
 $(document).on('click','.shift-edit-btn',function(){resetShiftForm();editShiftId=$(this).data('id');const p=JSON.parse(atob($(this).data('payload')));$('#shiftModalTitle').text('Edit Shift');$('#shiftSaveText').text('Update Shift');$('#shiftName').val(p.name);$('#shiftCode').val(p.code);$('#shiftStart').val(p.start_time);$('#shiftEnd').val(p.end_time);$('#shiftBreak').val(p.break_minutes);$('#shiftGrace').val(p.grace_minutes);$('#shiftSort').val(p.sort_order);$('#shiftNotes').val(p.notes);$('#shiftOvernight').prop('checked',!!p.is_overnight);$('#shiftStatus').prop('checked',!!p.status);modal.show();});
 $('#shiftForm').on('submit',function(e){e.preventDefault();const data=$(this).serializeArray();data.push({name:'status',value:$('#shiftStatus').is(':checked')?1:0},{name:'is_overnight',value:$('#shiftOvernight').is(':checked')?1:0});const url=editShiftId?"{{ url('/hr/shifts') }}/"+editShiftId:"{{ route('hr.shifts.store') }}",type=editShiftId?'PUT':'POST';const btn=$('#shiftSaveBtn').prop('disabled',true);$('.shift-error').text('');$.ajax({url,type,data:$.param(data)}).done(res=>{modal.hide();showToast('Saved',res.message);loadShifts(shiftPage)}).fail(xhr=>{const errors=xhr.responseJSON?.errors||{};Object.keys(errors).forEach(k=>$('[data-error="'+k+'"]').text(errors[k][0]));Swal.fire('Could not save',xhr.responseJSON?.message||'Please check the form.','error')}).always(()=>btn.prop('disabled',false));});
 $(document).on('change','.shift-status-toggle',function(){const id=$(this).data('id'),el=this;$.ajax({url:"{{ url('/hr/shifts') }}/"+id+'/status',type:'PATCH',data:{_token:"{{ csrf_token() }}",status:this.checked?1:0}}).done(res=>showToast('Updated',res.message)).fail(xhr=>{el.checked=!el.checked;Swal.fire('Error',xhr.responseJSON?.message||'Failed.','error')})});
 $(document).on('click','.shift-delete-btn',function(){const id=$(this).data('id');Swal.fire({title:'Delete shift?',text:'Assigned shifts cannot be deleted.',icon:'warning',showCancelButton:true,confirmButtonText:'Delete',confirmButtonColor:'#c63d3d'}).then(r=>{if(!r.isConfirmed)return;$.ajax({url:"{{ url('/hr/shifts') }}/"+id,type:'DELETE',data:{_token:"{{ csrf_token() }}"}}).done(res=>{showToast('Deleted',res.message);loadShifts(shiftPage)}).fail(xhr=>Swal.fire('Cannot delete',xhr.responseJSON?.message||'Failed.','error'))})});
 function loadRoster(p=1){rosterPage=p;$('#rosterTableContainer').addClass('hr-table-loading');$.get("{{ route('hr.shifts.roster.table') }}",{page:p,week_start:$('#rosterWeekStart').val(),search:$('#rosterSearch').val(),department_id:cv('rosterDepartment')}).done(function(html){const container=$('#rosterTableContainer');container.html(html);HrUi.initSelect2(container);}).fail(()=>Swal.fire('Error','Failed to load duty roster.','error')).always(()=>$('#rosterTableContainer').removeClass('hr-table-loading'));}
 $('#rosterSearch').on('input',()=>{clearTimeout(rosterTimer);rosterTimer=setTimeout(()=>loadRoster(1),350)});$('#rosterDepartment').on('change',()=>loadRoster(1));$('#rosterReset').on('click',function(){$('#rosterSearch').val('');HrUi.resetSelect('rosterDepartment');weekPicker.setDate(new Date(),true);});$(document).on('click','#rosterTableContainer .report-page-link:not(.disabled)',function(e){e.preventDefault();const u=new URL(this.href);loadRoster(u.searchParams.get('page')||1)});$(document).on('change','.roster-select',function(){$(this).closest('tr').addClass('attendance-row-dirty')});
 $('#saveRosterBtn').on('click',function(){const rows=[];$('#rosterTableContainer tbody tr[data-employee-id]').each(function(){const r=$(this),assignments=[];r.find('.roster-select').each(function(){assignments.push({date:$(this).data('date'),value:$(this).val()})});rows.push({employee_id:r.data('employee-id'),assignments})});if(!rows.length)return Swal.fire('No records','No employee records are visible.','info');const btn=$(this).prop('disabled',true);$.ajax({url:"{{ route('hr.shifts.roster.save') }}",type:'POST',contentType:'application/json',data:JSON.stringify({_token:"{{ csrf_token() }}",week_start:$('#rosterWeekStart').val(),rows})}).done(res=>{showToast('Saved',res.message);loadRoster(rosterPage)}).fail(xhr=>Swal.fire('Could not save',xhr.responseJSON?.message||'Failed.','error')).always(()=>btn.prop('disabled',false));});
 $('#copyRosterBtn').on('click',function(){Swal.fire({title:'Copy previous week?',text:'Existing entries in the selected week will be overwritten where previous entries exist.',icon:'question',showCancelButton:true,confirmButtonText:'Copy'}).then(r=>{if(!r.isConfirmed)return;$.post("{{ route('hr.shifts.roster.copy') }}",{_token:"{{ csrf_token() }}",week_start:$('#rosterWeekStart').val()}).done(res=>{showToast('Copied',res.message);loadRoster(1)}).fail(xhr=>Swal.fire('Could not copy',xhr.responseJSON?.message||'Failed.','error'))})});
 loadShifts();
});
</script>
@endsection
