@extends('admin.master.master')
@section('title','Inventory Ingredients')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Ingredients</h1><p class="text-muted mb-0">Global ingredient master with base-unit rules and ingredient-specific package conversions.</p></div><a href="{{ route('inventory.ingredients.create') }}" class="progga-btn progga-btn-primary"><i class="bi bi-plus-lg"></i> Add Ingredient</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    <div class="progga-card mb-4 inventory-filter-card"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-md-4"><label class="progga-form-label">Measurement Type</label><select class="progga-form-control" name="dimension"><option value="">All measurement types</option>@foreach(['WEIGHT','VOLUME','COUNT'] as $d)<option value="{{ $d }}" @selected(request('dimension')===$d)>{{ $d }}</option>@endforeach</select></div><div class="col-md-auto"><button class="progga-btn progga-btn-secondary">Apply Filter</button></div><div class="col-md-auto"><a class="progga-btn progga-btn-light" href="{{ route('inventory.ingredients.index') }}">Clear</a></div></form></div></div>
    <div class="progga-card">
        <div class="progga-card-header inventory-list-toolbar"><div class="inventory-result-copy"><span class="fw-semibold">Ingredient List</span><small class="text-muted" id="inventoryResultCount">{{ $ingredients->total() }} {{ $ingredients->total() === 1 ? 'record' : 'records' }}</small></div><div class="inventory-search-wrap"><i class="bi bi-search inventory-search-icon"></i><input type="search" id="inventorySearch" class="progga-form-control inventory-search-input" value="{{ request('search') }}" placeholder="Search ingredient or code..." autocomplete="off"><button type="button" id="inventorySearchClear" class="inventory-search-clear"><i class="bi bi-x-lg"></i></button></div></div>
        <div id="inventoryListContent"><div class="progga-table-wrapper" style="border:none;border-radius:0;"><table class="progga-table"><thead><tr><th style="width:70px;">SL</th><th>Ingredient</th><th>Type</th><th>Base Unit</th><th>Low Stock</th><th>Package Conversions</th><th>Tracking</th><th>Status</th><th style="width:100px;">Actions</th></tr></thead><tbody>
        @forelse($ingredients as $ingredient)<tr><td>{{ ($ingredients->firstItem() ?? 1)+$loop->index }}</td><td><strong>{{ $ingredient->name }}</strong><br><small class="text-muted">{{ $ingredient->code ?: 'No code' }}</small></td><td><span class="progga-badge progga-badge-info">{{ $ingredient->measurement_dimension }}</span></td><td>{{ $ingredient->baseUnit?->name }} ({{ $ingredient->baseUnit?->symbol }})</td><td>{{ number_format((float) $ingredient->low_stock_level_base, 2, '.', '') }} {{ $ingredient->baseUnit?->symbol }}</td><td>@forelse($ingredient->unitConversions->where('is_active',true) as $conversion)<span class="progga-badge progga-badge-neutral me-1" title="1 {{ $conversion->unit?->symbol }} = {{ number_format((float) $conversion->factor_to_base, 2, '.', '') }} {{ $ingredient->baseUnit?->symbol }}">{{ $conversion->label ?: ($conversion->unit?->name.' ('.rtrim(rtrim((string)$conversion->factor_to_base,'0'),'.').' '.$ingredient->baseUnit?->symbol.')') }}</span>@empty<span class="text-muted">—</span>@endforelse</td><td><span class="progga-badge progga-badge-{{ $ingredient->track_inventory?'success':'neutral' }}">{{ $ingredient->track_inventory?'ON':'OFF' }}</span></td><td><span class="progga-badge progga-badge-{{ $ingredient->is_active?'success':'neutral' }}">{{ $ingredient->is_active?'Active':'Inactive' }}</span></td><td><div class="progga-table-actions"><a href="{{ route('inventory.ingredients.edit',$ingredient) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Edit"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('inventory.ingredients.destroy',$ingredient) }}" class="d-inline">@csrf @method('DELETE')<button type="button" class="progga-btn progga-btn-danger progga-btn-icon progga-btn-sm" title="Delete" data-delete-name="{{ $ingredient->name }}" onclick="inventoryConfirmDelete(this)"><i class="bi bi-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-5">No ingredients found.</td></tr>@endforelse
        </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$ingredients,'label'=>'ingredients'])</div>
    </div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.ingredients.index')])
@endsection
