<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
body{font-family:dejavusans,sans-serif;color:#1e2924;font-size:9px}.header{border-bottom:3px solid #21352a;padding-bottom:8px;margin-bottom:10px}.brand{font-size:18px;font-weight:bold;color:#21352a}.title{text-align:right;font-size:18px;font-weight:bold;color:#21352a}.muted{color:#6b7c74}.summary{width:100%;border-collapse:collapse;margin:10px 0}.summary td{padding:8px;border:1px solid #dfe5e1;text-align:center}.summary strong{font-size:13px;color:#21352a}.table{width:100%;border-collapse:collapse}.table th{background:#21352a;color:#fff;padding:6px 4px;text-align:left}.table td{border:1px solid #dfe5e1;padding:5px 4px}.right{text-align:right}.center{text-align:center}.paid{color:#16814b;font-weight:bold}.unpaid{color:#a86800;font-weight:bold}.total{background:#eef2ef;font-weight:bold}.small{font-size:8px}
</style>
</head>
<body>
<table class="header" width="100%"><tr><td><div class="brand">{{ $restaurant->restaurant_name ?? $restaurant->name ?? config('app.name') }}</div><div class="muted">{{ $restaurant->address ?? '' }}</div></td><td class="title">PAYROLL SUMMARY<div class="muted" style="font-size:10px;font-weight:normal">{{ $run->month_label }} · {{ $run->payroll_code }}</div></td></tr></table>

<table class="summary"><tr><td><span class="muted">Employees</span><br><strong>{{ $run->total_employees }}</strong></td><td><span class="muted">Gross Salary</span><br><strong>৳{{ number_format((float) $run->total_gross, 2) }}</strong></td><td><span class="muted">Deduction</span><br><strong>৳{{ number_format((float) $run->total_deduction, 2) }}</strong></td><td><span class="muted">Net Payable</span><br><strong>৳{{ number_format((float) $run->total_net, 2) }}</strong></td><td><span class="muted">Paid</span><br><strong>৳{{ number_format((float) $run->total_paid, 2) }}</strong></td></tr></table>

<table class="table">
<thead><tr><th>#</th><th>Employee</th><th>Department</th><th class="center">P</th><th class="center">L</th><th class="center">A</th><th class="center">HD</th><th class="right">Basic</th><th class="right">Gross</th><th class="right">Deduction</th><th class="right">Net</th><th class="center">Workflow</th><th class="center">Payment</th></tr></thead>
<tbody>
@foreach($run->items as $index => $item)
<tr><td>{{ $index + 1 }}</td><td><strong>{{ $item->employee_name }}</strong><br><span class="small">{{ $item->employee_code }}</span></td><td>{{ $item->department_name ?: 'N/A' }}</td><td class="center">{{ (float) $item->present_days }}</td><td class="center">{{ (float) $item->late_days }}</td><td class="center">{{ (float) $item->absent_days }}</td><td class="center">{{ (float) $item->half_days }}</td><td class="right">{{ number_format((float) $item->prorated_basic_salary, 2) }}</td><td class="right">{{ number_format((float) $item->gross_salary, 2) }}</td><td class="right">{{ number_format((float) $item->total_deduction, 2) }}</td><td class="right"><strong>{{ number_format((float) $item->net_salary, 2) }}</strong></td><td class="center">{{ strtoupper($item->status) }}</td><td class="center {{ $item->payment_status === 'paid' ? 'paid' : 'unpaid' }}">{{ strtoupper($item->payment_status) }}</td></tr>
@endforeach
<tr class="total"><td colspan="8" class="right">TOTAL</td><td class="right">৳{{ number_format((float) $run->total_gross, 2) }}</td><td class="right">৳{{ number_format((float) $run->total_deduction, 2) }}</td><td class="right">৳{{ number_format((float) $run->total_net, 2) }}</td><td></td><td></td></tr>
</tbody></table>

<div style="margin-top:10px"><strong>Status:</strong> {{ strtoupper($run->status) }} · <strong>Period:</strong> {{ $run->period_start->format('d-m-Y') }} to {{ $run->period_end->format('d-m-Y') }} · <strong>Generated by:</strong> {{ $run->generatedBy->name ?? 'System' }}</div>
</body>
</html>
