<div class="progga-card">
    <div class="progga-card-header">
        <div>
            <div class="progga-card-title"><i class="bi bi-fingerprint me-2"></i>Attendance Rules</div>
            <div class="hr-settings-help">These rules will be used to calculate late, half-day, absence and overtime.</div>
        </div>
    </div>
    <div class="progga-card-body">
        <form action="{{ route('hr.settings.attendance.update') }}" method="POST">
            @csrf
            <div class="row g-3">
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Grace Time</label><div class="input-group"><input type="number" name="grace_minutes" class="progga-form-control" min="0" max="240" value="{{ old('grace_minutes', $attendanceSetting->grace_minutes ?? 10) }}"><span class="input-group-text">Minutes</span></div><div class="hr-settings-help">Arrival within this time is not considered late.</div></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Half Day After</label><div class="input-group"><input type="number" name="half_day_after_minutes" class="progga-form-control" min="1" max="1440" value="{{ old('half_day_after_minutes', $attendanceSetting->half_day_after_minutes ?? 240) }}"><span class="input-group-text">Minutes</span></div></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Absent After</label><div class="input-group"><input type="number" name="absent_after_minutes" class="progga-form-control" min="1" max="1440" value="{{ old('absent_after_minutes', $attendanceSetting->absent_after_minutes ?? 480) }}"><span class="input-group-text">Minutes</span></div></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Minimum Overtime</label><div class="input-group"><input type="number" name="minimum_overtime_minutes" class="progga-form-control" min="0" max="480" value="{{ old('minimum_overtime_minutes', $attendanceSetting->minimum_overtime_minutes ?? 30) }}"><span class="input-group-text">Minutes</span></div></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Default Working Hours</label><div class="input-group"><input type="number" step="0.25" name="default_working_hours" class="progga-form-control" min="1" max="24" value="{{ old('default_working_hours', $attendanceSetting->default_working_hours ?? 8) }}"><span class="input-group-text">Hours</span></div></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Weekly Off Days</label><select id="hrWeeklyOffDays" name="weekly_off_days[]" class="progga-select hr-select2" multiple>@php($selectedOffDays = old('weekly_off_days', $attendanceSetting->weekly_off_days ?? ['Friday']))@foreach(['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday'] as $day)<option value="{{ $day }}" {{ in_array($day, $selectedOffDays ?? []) ? 'selected' : '' }}>{{ $day }}</option>@endforeach</select><div class="hr-settings-help">Select one or more weekly off days.</div></div></div>

                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Manual Attendance</label><label class="progga-toggle" style="margin-top:8px;"><input type="checkbox" name="allow_manual_attendance" value="1" {{ old('allow_manual_attendance', $attendanceSetting->allow_manual_attendance ?? true) ? 'checked' : '' }} data-on="Allowed" data-off="Disabled"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">{{ old('allow_manual_attendance', $attendanceSetting->allow_manual_attendance ?? true) ? 'Allowed' : 'Disabled' }}</span></label></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Automatic Late Calculation</label><label class="progga-toggle" style="margin-top:8px;"><input type="checkbox" name="auto_calculate_late" value="1" {{ old('auto_calculate_late', $attendanceSetting->auto_calculate_late ?? true) ? 'checked' : '' }} data-on="Enabled" data-off="Disabled"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">{{ old('auto_calculate_late', $attendanceSetting->auto_calculate_late ?? true) ? 'Enabled' : 'Disabled' }}</span></label></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Automatic Overtime Calculation</label><label class="progga-toggle" style="margin-top:8px;"><input type="checkbox" name="auto_calculate_overtime" value="1" {{ old('auto_calculate_overtime', $attendanceSetting->auto_calculate_overtime ?? true) ? 'checked' : '' }} data-on="Enabled" data-off="Disabled"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">{{ old('auto_calculate_overtime', $attendanceSetting->auto_calculate_overtime ?? true) ? 'Enabled' : 'Disabled' }}</span></label></div></div>
            </div>
            @can('hr-setting-update')<div class="d-flex justify-content-end mt-4"><button type="submit" class="progga-btn progga-btn-primary"><i class="bi bi-check-lg"></i> Save Attendance Rules</button></div>@endcan
        </form>
    </div>
</div>
