<div class="modal fade hr-modal" id="employeeModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content">
<form id="employeeForm" enctype="multipart/form-data">@csrf<input type="hidden" id="employeeFormMethod" value="POST">
<div class="modal-header"><div><h5 class="modal-title" id="employeeModalTitle">Add Employee</h5><div style="font-size:11px;opacity:.75">Employee ID: <span id="employeeIdPreview">Auto generated</span></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="row g-3">
<div class="col-lg-3"><div class="text-center p-3" style="border:1px dashed var(--progga-border);border-radius:14px;background:#fafbfa"><img id="employeeImagePreview" src="https://ui-avatars.com/api/?name=Employee&background=21352a&color=d5aa65&size=100" style="width:100px;height:100px;border-radius:18px;object-fit:cover"><label class="progga-btn progga-btn-outline progga-btn-sm mt-3" for="employeeImage"><i class="bi bi-camera"></i> Choose Photo</label><input type="file" class="d-none" name="image" id="employeeImage" accept="image/*"><div class="employee-error text-danger mt-1" data-error="image"></div></div></div>
<div class="col-lg-9"><div class="hr-section-title">Personal Information</div><div class="row g-3">
<div class="col-md-6"><label class="progga-form-label">Full Name <span class="progga-required">*</span></label><input class="progga-form-control" name="name" id="employeeName"><div class="employee-error text-danger" data-error="name"></div></div>
<div class="col-md-3"><label class="progga-form-label">Phone <span class="progga-required">*</span></label><input class="progga-form-control" name="phone" id="employeePhone"><div class="employee-error text-danger" data-error="phone"></div></div>
<div class="col-md-3"><label class="progga-form-label">Gender</label><select id="formGender" class="employee-choice"><option value="">Select</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></div>
<div class="col-md-4"><label class="progga-form-label">Date of Birth</label><input class="progga-form-control employee-date" name="date_of_birth" id="employeeDob"></div>
<div class="col-md-8"><label class="progga-form-label">Address</label><input class="progga-form-control" name="address" id="employeeAddress"></div>
</div></div>
<div class="col-12"><div class="hr-section-title">Employment Information</div><div class="row g-3">
<div class="col-md-4"><label class="progga-form-label">Department <span class="progga-required">*</span></label><select id="formDepartment" class="employee-choice"><option value="">Select Department</option>@foreach($departments as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select><div class="employee-error text-danger" data-error="department_id"></div></div>
<div class="col-md-4"><label class="progga-form-label">Designation <span class="progga-required">*</span></label><select id="formDesignation" class="employee-choice"><option value="">Select Designation</option>@foreach($designations as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select><div class="employee-error text-danger" data-error="designation_id"></div></div>
<div class="col-md-4"><label class="progga-form-label">Employment Type <span class="progga-required">*</span></label><select id="formEmploymentType" class="employee-choice"><option value="">Select Type</option>@foreach($employmentTypes as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select><div class="employee-error text-danger" data-error="employment_type_id"></div></div>
<div class="col-md-3"><label class="progga-form-label">Joining Date <span class="progga-required">*</span></label><input class="progga-form-control employee-date" name="join_date" id="employeeJoinDate"><div class="employee-error text-danger" data-error="join_date"></div></div>
<div class="col-md-3"><label class="progga-form-label">Probation End</label><input class="progga-form-control employee-date" name="probation_end_date" id="employeeProbationEnd"></div>
<div class="col-md-3"><label class="progga-form-label">Default Shift</label><select id="formShift" class="employee-choice"><option value="">No Default Shift</option>@foreach($shifts as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="progga-form-label">Status</label><select id="formStatus" class="employee-choice"><option value="active">Active</option><option value="inactive">Inactive</option><option value="resigned">Resigned</option><option value="terminated">Terminated</option></select></div>
<div class="col-md-3"><label class="progga-form-label">Exit Date</label><input class="progga-form-control employee-date" name="exit_date" id="employeeExitDate"></div>
</div></div>
<div class="col-12"><div class="hr-section-title">Access & Operational Role</div><div class="row g-3">
<div class="col-md-6"><div class="p-3 h-100" style="border:1px solid var(--progga-border-light);border-radius:13px"><label class="progga-toggle"><input type="checkbox" id="employeeIsWaiter"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label" style="font-weight:800">Waiter / POS Access</span></label><div class="hr-muted mt-2">Creates or links a waiter record without changing existing POS order history.</div><div id="waiterFields" class="mt-3" style="display:none"><label class="progga-form-label">Assigned Zone <span class="progga-required">*</span></label><select id="formZone" class="employee-choice"><option value="">Select Zone</option>@foreach($zones as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select><div class="employee-error text-danger" data-error="zone_id"></div></div></div></div>
<div class="col-md-6"><div class="p-3 h-100" style="border:1px solid var(--progga-border-light);border-radius:13px"><label class="progga-toggle"><input type="checkbox" id="employeeCanLogin"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label" style="font-weight:800">Can Login to System</span></label><div class="hr-muted mt-2">Create a secure system account. Login is blocked automatically when disabled or inactive.</div><div id="loginFields" class="row g-2 mt-1" style="display:none"><div class="col-12"><label class="progga-form-label">Login Email</label><input type="email" class="progga-form-control" name="email" id="employeeEmail"><div class="employee-error text-danger" data-error="email"></div></div><div class="col-md-6"><label class="progga-form-label">Password</label><input type="password" class="progga-form-control" name="password" id="employeePassword"><div class="employee-error text-danger" data-error="password"></div></div><div class="col-md-6"><label class="progga-form-label">Confirm Password</label><input type="password" class="progga-form-control" name="password_confirmation"></div></div></div></div>
</div></div>
<div class="col-12"><div class="hr-section-title">Emergency & Notes</div><div class="row g-3"><div class="col-md-4"><label class="progga-form-label">Emergency Contact Name</label><input class="progga-form-control" name="emergency_contact_name" id="employeeEmergencyName"></div><div class="col-md-4"><label class="progga-form-label">Emergency Contact Phone</label><input class="progga-form-control" name="emergency_contact_phone" id="employeeEmergencyPhone"></div><div class="col-md-4"><label class="progga-form-label">Notes</label><input class="progga-form-control" name="notes" id="employeeNotes"></div></div></div>
</div></div>
<div class="modal-footer"><button type="button" class="progga-btn progga-btn-outline" data-bs-dismiss="modal">Cancel</button><button type="submit" class="progga-btn progga-btn-primary" id="employeeSaveBtn"><i class="bi bi-check-lg"></i> <span id="employeeSaveText">Save Employee</span></button></div>
</form></div></div></div>
