@extends('admin.master.master')
@php $oldItems=old('items',[['ingredient_id'=>'','quantity'=>'','unit_choice'=>'']]); @endphp
@section('title','Post Inventory Wastage')
@section('body')
@php $kitchenActor = auth()->user()?->isKitchenUser() ?? false; $kitchenLocation = $kitchenActor ? $locations->first() : null; @endphp
<main class="progga-content"><div class="progga-page-header"><div><h1 class="progga-page-title">Post Wastage</h1><p class="text-muted mb-0">Wastage reduces only the selected branch stock location and creates immutable evidence in the ledger.</p></div><a href="{{ route('inventory.wastages.index') }}" class="progga-btn progga-btn-outline">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('inventory.wastages.store') }}" onsubmit="return confirm('Post this wastage? Posted records cannot be edited directly.')">@csrf
<div class="progga-card mb-4"><div class="p-4"><div class="row g-3"><div class="col-md-4"><label class="progga-form-label">Stock Location</label>@if($kitchenActor)<input type="hidden" id="wasteLocation" name="location_id" value="{{ $kitchenLocation?->id }}"><div class="progga-form-control bg-light">{{ $kitchenLocation?->name ?: 'Kitchen Stock' }} (KITCHEN)</div><small class="text-muted">Kitchen users can post wastage only from Kitchen Stock.</small>@else<select id="wasteLocation" name="location_id" class="progga-form-control" onchange="refreshWasteAvailable()" required><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)old('location_id')===(string)$location->id)>{{ $location->name }} ({{ $location->type }})</option>@endforeach</select>@endif</div><div class="col-md-4"><label class="progga-form-label">Reason</label><select name="reason_code" class="progga-form-control" required><option value="">Select reason</option>@foreach($reasons as $reason)<option value="{{ $reason }}" @selected(old('reason_code')===$reason)>{{ ucfirst(strtolower($reason)) }}</option>@endforeach</select></div><div class="col-md-4"><label class="progga-form-label">Notes</label><input name="notes" value="{{ old('notes') }}" class="progga-form-control" placeholder="Required for Other"></div></div></div></div>
<div class="progga-card mb-4"><div class="progga-card-header d-flex justify-content-between"><div><strong>Wastage Items</strong><div class="small text-muted">Available stock is informational; the server validates again under lock.</div></div><button type="button" class="progga-btn progga-btn-secondary progga-btn-sm" onclick="addWasteRow()">Add Item</button></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ingredient</th><th style="width:160px">Available</th><th style="width:170px">Quantity</th><th style="width:220px">Unit</th><th style="width:60px"></th></tr></thead><tbody id="wasteRows">@foreach($oldItems as $idx=>$row)<tr class="waste-row"><td><select name="items[{{ $idx }}][ingredient_id]" class="progga-form-control waste-ingredient" onchange="filterWasteUnits(this);refreshWasteAvailable()" required><option value="">Select ingredient</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" data-dimension="{{ $ingredient->measurement_dimension }}" data-packages="{{ $ingredient->unitConversions->pluck('unit_id')->implode(',') }}" data-base="{{ $ingredient->baseUnit?->symbol }}" @selected((string)($row['ingredient_id']??'')===(string)$ingredient->id)>{{ $ingredient->name }} ({{ $ingredient->baseUnit?->symbol }})</option>@endforeach</select></td><td class="waste-available text-muted">—</td><td><input type="number" step="0.00000001" min="0.00000001" name="items[{{ $idx }}][quantity]" value="{{ $row['quantity']??'' }}" class="progga-form-control" required></td><td><select name="items[{{ $idx }}][unit_choice]" class="progga-form-control waste-unit" data-selected="{{ $row['unit_choice']??'' }}" required><option value="">Select ingredient first</option></select></td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeWasteRow(this)"><i class="bi bi-trash"></i></button></td></tr>@endforeach</tbody></table></div></div>
<div class="d-flex justify-content-end"><button class="progga-btn progga-btn-primary">Post Wastage</button></div></form></main>
@endsection
@section('script')
<script>
const wIngredients={{ \Illuminate\Support\Js::from($ingredients->map(fn($i)=>[
    'id'=>$i->id,'name'=>$i->name,'base'=>$i->baseUnit?->symbol,'dimension'=>$i->measurement_dimension,
    'packages'=>$i->unitConversions->map(fn($c)=>['id'=>(int)$c->id,'label'=>$c->label ?: (($c->unit?->name ?? 'Package').' ('.rtrim(rtrim((string)$c->factor_to_base,'0'),'.').' '.$i->baseUnit?->symbol.')')])->values()
])->values()) }};
const wUnits={{ \Illuminate\Support\Js::from($units->where('dimension','!=','PACKAGE')->map(fn($u)=>['id'=>$u->id,'name'=>$u->name,'symbol'=>$u->symbol,'dimension'=>$u->dimension])->values()) }};
const wAvail={{ \Illuminate\Support\Js::from($available) }};let wIndex={{ count($oldItems) }};
function we(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function wTrimQty(v){const n=String(v??'0');return n.includes('.')?(n.replace(/0+$/,'').replace(/\.$/,'')):(n||'0');}
function wi(){return '<option value="">Select ingredient</option>'+wIngredients.map(i=>`<option value="${i.id}" data-base="${we(i.base)}">${we(i.name)} (${we(i.base)})</option>`).join('');}
function wasteUnitOptions(ingredientId){const i=wIngredients.find(x=>String(x.id)===String(ingredientId));if(!i)return '<option value="">Select ingredient first</option>';let html='<option value="">Select unit / package size</option>';html+=wUnits.filter(u=>u.dimension===i.dimension).map(u=>`<option value="u:${u.id}">${we(u.name)} (${we(u.symbol)})</option>`).join('');if(i.packages.length)html+='<optgroup label="Package variants">'+i.packages.map(p=>`<option value="c:${p.id}">${we(p.label)}</option>`).join('')+'</optgroup>';return html;}
function addWasteRow(){const tr=document.createElement('tr');tr.className='waste-row';tr.innerHTML=`<td><select name="items[${wIndex}][ingredient_id]" class="progga-form-control waste-ingredient" onchange="filterWasteUnits(this);refreshWasteAvailable()" required>${wi()}</select></td><td class="waste-available text-muted">—</td><td><input type="number" step="0.00000001" min="0.00000001" name="items[${wIndex}][quantity]" class="progga-form-control" required></td><td><select name="items[${wIndex}][unit_choice]" class="progga-form-control waste-unit" required><option value="">Select ingredient first</option></select></td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeWasteRow(this)"><i class="bi bi-trash"></i></button></td>`;document.getElementById('wasteRows').appendChild(tr);wIndex++;}
function removeWasteRow(b){if(document.querySelectorAll('.waste-row').length<=1)return;b.closest('tr').remove();}
function filterWasteUnits(s){const row=s.closest('.waste-row'),u=row.querySelector('.waste-unit'),wanted=u.dataset.selected||u.value;u.innerHTML=wasteUnitOptions(s.value);if(wanted&&[...u.options].some(x=>x.value===wanted))u.value=wanted;u.dataset.selected='';}
function refreshWasteAvailable(){const loc=document.getElementById('wasteLocation')?.value||'';document.querySelectorAll('.waste-row').forEach(row=>{const s=row.querySelector('.waste-ingredient'),id=s.value,i=wIngredients.find(x=>String(x.id)===String(id)),base=i?.base||'',q=(wAvail[loc]&&wAvail[loc][id])?wAvail[loc][id]:'0.00000000';row.querySelector('.waste-available').textContent=id?`${wTrimQty(q)} ${base}`:'—';});}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.waste-ingredient').forEach(filterWasteUnits);refreshWasteAvailable();});
</script>
@endsection
