<style>
.hr-shell{position:relative}.hr-shell:before{content:"";position:absolute;inset:-24px -20px auto;height:190px;border-radius:0 0 28px 28px;background:linear-gradient(135deg,rgba(33,53,42,.07),rgba(213,170,101,.11));pointer-events:none}.hr-shell>*{position:relative;z-index:1}
.hr-stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}.hr-stat-card{background:#fff;border:1px solid rgba(33,53,42,.1);border-radius:16px;padding:17px;display:flex;align-items:center;gap:13px;box-shadow:0 8px 24px rgba(33,53,42,.06)}.hr-stat-icon{width:48px;height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,rgba(33,53,42,.12),rgba(213,170,101,.2));color:var(--progga-primary);font-size:20px}.hr-stat-value{font-size:22px;font-weight:900;color:var(--progga-text);line-height:1}.hr-stat-label{font-size:12px;color:var(--progga-text-muted);margin-top:5px}
.hr-card{background:#fff;border:1px solid rgba(33,53,42,.1);border-radius:16px;box-shadow:0 10px 28px rgba(33,53,42,.065);overflow:hidden}.hr-card-header{padding:17px 19px;border-bottom:1px solid rgba(33,53,42,.08);display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;background:linear-gradient(180deg,#fff,rgba(33,53,42,.02))}.hr-card-title{font-size:16px;font-weight:900;color:var(--progga-text)}.hr-card-subtitle{font-size:12px;color:var(--progga-text-muted);margin-top:3px}.hr-card-body{padding:18px}.hr-filter-grid{display:grid;grid-template-columns:2fr repeat(3,minmax(150px,1fr)) auto;gap:10px;align-items:end}.hr-filter-grid.five{grid-template-columns:2fr repeat(4,minmax(140px,1fr)) auto}.hr-search{position:relative}.hr-search i{position:absolute;left:13px;top:50%;transform:translateY(-50%);color:var(--progga-text-muted)}.hr-search input{padding-left:38px}.hr-table-loading{opacity:.55;pointer-events:none}.hr-table-avatar{width:40px;height:40px;border-radius:12px;object-fit:cover;flex-shrink:0}.hr-person{display:flex;align-items:center;gap:11px}.hr-person-name{font-weight:800;color:var(--progga-text)}.hr-person-meta{font-size:11px;color:var(--progga-text-muted);margin-top:2px}.hr-muted{font-size:12px;color:var(--progga-text-muted)}
.hr-badge{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800;text-transform:capitalize}.hr-badge-success{background:#e7f7ed;color:#16814b}.hr-badge-danger{background:#fdeaea;color:#c63d3d}.hr-badge-warning{background:#fff3dd;color:#a86800}.hr-badge-info{background:#e9f4ff;color:#1768a7}.hr-badge-neutral{background:#f1f3f2;color:#53615a}.hr-badge-primary{background:rgba(33,53,42,.1);color:var(--progga-primary)}
.report-pagination-wrap{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:14px 16px;border-top:1px solid var(--progga-border-light)}.report-pagination{display:flex;gap:5px;align-items:center;flex-wrap:wrap}.report-page-link{display:inline-flex;align-items:center;justify-content:center;min-width:34px;height:34px;padding:0 10px;border:1px solid var(--progga-border-light);border-radius:8px;background:#fff;color:var(--progga-primary);font-size:12px;font-weight:800;text-decoration:none}.report-page-link:hover{background:rgba(33,53,42,.06);color:var(--progga-primary)}.report-page-link.active{background:var(--progga-primary);color:#fff;border-color:var(--progga-primary)}.report-page-link.disabled{opacity:.45;pointer-events:none;color:var(--progga-text-muted)}
.hr-modal .modal-content{border:0;border-radius:17px;overflow:hidden;box-shadow:0 24px 70px rgba(0,0,0,.18)}.hr-modal .modal-header{padding:17px 20px;background:linear-gradient(135deg,var(--progga-primary),#355b46);color:#fff;border:0}.hr-modal .modal-header .btn-close{filter:invert(1)}.hr-modal .modal-body{padding:20px}.hr-modal .modal-footer{padding:14px 20px 18px}.hr-section-title{font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.06em;color:var(--progga-primary);margin:5px 0 12px;padding-bottom:8px;border-bottom:1px solid rgba(33,53,42,.1)}
.hr-shell .select2-container{width:100%!important;min-width:0}.hr-shell .select2-container--progga-theme .select2-selection--single{height:42px}.hr-shell .select2-container--progga-theme .select2-selection--single .select2-selection__rendered{line-height:40px}.hr-shell .select2-container--progga-theme .select2-selection--single .select2-selection__arrow{height:40px}.hr-modal .select2-container{width:100%!important}.select2-container--open{z-index:2100!important}.flatpickr-day.selected{background:var(--progga-primary);border-color:var(--progga-primary)}
.hr-segmented{display:flex;gap:7px;padding:5px;background:rgba(33,53,42,.05);border-radius:11px;flex-wrap:wrap}.hr-segmented button{border:0;background:transparent;padding:8px 13px;border-radius:8px;font-size:12px;font-weight:800;color:var(--progga-text-muted)}.hr-segmented button.active{background:#fff;color:var(--progga-primary);box-shadow:0 3px 12px rgba(33,53,42,.1)}
.hr-empty{padding:42px 18px;text-align:center;color:var(--progga-text-muted)}.hr-empty i{display:block;font-size:30px;margin-bottom:8px;color:rgba(33,53,42,.35)}
@media(max-width:1199px){.hr-filter-grid,.hr-filter-grid.five{grid-template-columns:repeat(3,minmax(0,1fr))}.hr-search{grid-column:span 2}.hr-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:767px){.hr-filter-grid,.hr-filter-grid.five{grid-template-columns:1fr}.hr-search{grid-column:auto}.hr-stat-grid{grid-template-columns:1fr}.hr-card-header .progga-btn{width:100%;justify-content:center}.report-pagination-wrap{align-items:flex-start}.report-pagination{width:100%}.report-page-link:first-child,.report-page-link:last-child{display:none}}
</style>


<style>
.hr-filter-grid-employees{display:grid;grid-template-columns:minmax(240px,2fr) repeat(5,minmax(145px,1fr)) auto;gap:10px;align-items:end}
.hr-profile-image{width:128px;height:128px;border-radius:22px;object-fit:cover;border:4px solid #fff;box-shadow:0 10px 28px rgba(33,53,42,.16)}
.hr-profile-image-lg{width:112px;height:112px;border-radius:24px;object-fit:cover;border:4px solid #fff;box-shadow:0 12px 30px rgba(33,53,42,.16);flex-shrink:0}
.hr-profile-hero{display:flex;align-items:center;gap:20px;padding:22px;background:linear-gradient(135deg,#fff,rgba(213,170,101,.12));border:1px solid rgba(33,53,42,.1);border-radius:18px;box-shadow:0 10px 28px rgba(33,53,42,.065)}
.hr-profile-code{font-size:13px;font-weight:800;color:var(--progga-text-muted);margin-top:4px}.hr-profile-contact{display:grid;gap:8px;font-size:13px;color:var(--progga-text-muted);min-width:220px}.hr-profile-contact i{color:var(--progga-primary);margin-right:7px}
.hr-option-card{height:100%;padding:16px;border:1px solid var(--progga-border-light);border-radius:14px;background:linear-gradient(180deg,#fff,rgba(33,53,42,.018))}
.hr-form-actions{display:flex;justify-content:flex-end;gap:10px;padding:15px 0;position:sticky;bottom:0;z-index:20;background:linear-gradient(180deg,rgba(247,248,247,0),#f7f8f7 35%)}
.hr-info-list{display:grid;gap:0}.hr-info-list>div{display:flex;justify-content:space-between;gap:18px;padding:10px 0;border-bottom:1px solid rgba(33,53,42,.08);font-size:13px}.hr-info-list>div:last-child{border-bottom:0}.hr-info-list span{color:var(--progga-text-muted)}.hr-info-list strong{text-align:right;color:var(--progga-text)}
.hr-money-box{padding:14px;border-radius:13px;background:rgba(33,53,42,.055);border:1px solid rgba(33,53,42,.08);display:flex;flex-direction:column;gap:4px}.hr-money-box span{font-size:11px;color:var(--progga-text-muted);text-transform:uppercase;letter-spacing:.04em}.hr-money-box strong{font-size:17px;color:var(--progga-primary)}
.hr-roster-strip{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px}.hr-roster-day{padding:11px 8px;border:1px solid var(--progga-border-light);border-radius:12px;text-align:center;background:#fff}.hr-roster-day span,.hr-roster-day small{display:block;font-size:10px;color:var(--progga-text-muted)}.hr-roster-day strong{display:block;font-size:13px;margin:3px 0;color:var(--progga-text)}
.hr-balance-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid rgba(33,53,42,.08)}.hr-balance-row:last-child{border-bottom:0}
.hr-estimated-gross{display:flex;align-items:flex-end;flex-direction:column;gap:2px;padding:9px 13px;border-radius:12px;background:rgba(33,53,42,.07)}.hr-estimated-gross span{font-size:10px;color:var(--progga-text-muted);text-transform:uppercase}.hr-estimated-gross strong{font-size:18px;color:var(--progga-primary)}
.hr-manual-component{font-size:12px;color:var(--progga-text-muted);padding:10px 12px;border-radius:9px;background:rgba(33,53,42,.045)}.salary-component-disabled{opacity:.52}.salary-component-disabled .hr-manual-component{pointer-events:none}
.hr-salary-component-table .input-group-text{font-size:12px;background:#f6f7f6;border-color:var(--progga-border-light)}
@media(max-width:1399px){.hr-filter-grid-employees{grid-template-columns:repeat(3,minmax(0,1fr))}.hr-filter-grid-employees .hr-search{grid-column:span 2}}
@media(max-width:991px){.hr-profile-hero{align-items:flex-start;flex-wrap:wrap}.hr-profile-contact{width:100%;min-width:0;grid-template-columns:repeat(3,minmax(0,1fr))}.hr-roster-strip{grid-template-columns:repeat(4,minmax(0,1fr))}}
@media(max-width:767px){.hr-filter-grid-employees{grid-template-columns:1fr}.hr-filter-grid-employees .hr-search{grid-column:auto}.hr-profile-hero{display:block;text-align:center}.hr-profile-image-lg{margin-bottom:14px}.hr-profile-contact{grid-template-columns:1fr;text-align:left;margin-top:16px}.hr-roster-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.hr-form-actions{position:static}.hr-form-actions .progga-btn{flex:1;justify-content:center}}
</style>

<style>
.payroll-run-filter{grid-template-columns:minmax(260px,2fr) minmax(170px,1fr) minmax(170px,1fr) auto}.payroll-item-filter{grid-template-columns:minmax(280px,2fr) minmax(190px,1fr) minmax(180px,1fr) auto}
.payroll-current-banner{background:linear-gradient(135deg,#fff,rgba(213,170,101,.14))}.payroll-run-hero{border-left:4px solid var(--progga-secondary)}
.payroll-five-stats{grid-template-columns:repeat(5,minmax(0,1fr))}.payroll-item-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.payroll-money{font-size:17px;white-space:nowrap}
.payroll-check-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.payroll-check-card{border:1px solid var(--progga-border-light);border-radius:13px;padding:14px;background:#fff}.payroll-check-card span{display:block;font-size:11px;text-transform:uppercase;color:var(--progga-text-muted);font-weight:800}.payroll-check-card strong{display:block;font-size:24px;color:var(--progga-primary);margin-top:4px}.payroll-check-card.warning{background:#fff9ef;border-color:#f1dfb8}
.payroll-step-list{display:grid;gap:13px}.payroll-step-list>div{display:flex;gap:11px;align-items:flex-start}.payroll-step-list>div>span{width:29px;height:29px;border-radius:9px;background:var(--progga-primary);color:#fff;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:900;flex-shrink:0}.payroll-step-list p{margin:0}.payroll-step-list strong,.payroll-step-list small{display:block}.payroll-step-list small{color:var(--progga-text-muted);margin-top:2px}
.payroll-missing-list{display:flex;gap:7px;flex-wrap:wrap}.payroll-missing-list a{padding:6px 9px;border-radius:8px;background:#fff;color:var(--progga-danger);font-size:11px;font-weight:800;border:1px solid rgba(179,48,48,.15)}
.payroll-confirm-row{display:flex;gap:12px;align-items:flex-start;border:1px solid var(--progga-border-light);border-radius:12px;padding:13px;margin-bottom:10px;cursor:pointer}.payroll-confirm-row input{margin-top:4px}.payroll-confirm-row strong,.payroll-confirm-row small{display:block}.payroll-confirm-row small{color:var(--progga-text-muted);margin-top:2px}
.payroll-attendance-chips{display:flex;gap:4px;flex-wrap:wrap}.payroll-attendance-chips span{font-size:10px;font-weight:900;padding:3px 6px;border-radius:7px;background:#f1f3f2;color:#53615a}.payroll-attendance-chips .good{background:#e7f7ed;color:#16814b}.payroll-attendance-chips .warn{background:#fff3dd;color:#a86800}.payroll-attendance-chips .bad{background:#fdeaea;color:#c63d3d}
.payroll-employee-hero{display:flex;align-items:center;gap:14px}.payroll-avatar{width:58px;height:58px;border-radius:18px;background:linear-gradient(135deg,var(--progga-primary),#355b46);color:var(--progga-secondary);display:flex;align-items:center;justify-content:center;font-size:23px;font-weight:900;flex-shrink:0}
.payroll-component-table .input-group-text{background:#f6f7f6;border-color:var(--progga-border-light)}.payroll-calculated-note{font-size:10px;color:var(--progga-text-muted);margin-top:4px}.payroll-overridden-row{background:#fff9ef}.payroll-overridden-row td:first-child{box-shadow:inset 3px 0 0 var(--progga-warning)}.payroll-payment-amount{border-radius:14px;background:rgba(33,53,42,.06);padding:15px;display:flex;align-items:center;justify-content:space-between}.payroll-payment-amount span{font-size:12px;color:var(--progga-text-muted)}.payroll-payment-amount strong{font-size:21px;color:var(--progga-primary)}
@media(max-width:1399px){.payroll-five-stats{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:1199px){.payroll-run-filter,.payroll-item-filter{grid-template-columns:repeat(2,minmax(0,1fr))}.payroll-run-filter .hr-search,.payroll-item-filter .hr-search{grid-column:span 2}.payroll-check-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.payroll-five-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:767px){.payroll-run-filter,.payroll-item-filter{grid-template-columns:1fr}.payroll-run-filter .hr-search,.payroll-item-filter .hr-search{grid-column:auto}.payroll-check-grid,.payroll-five-stats,.payroll-item-stats{grid-template-columns:1fr}.payroll-money{font-size:18px}}
</style>

<style>
.payroll-month-shortcuts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.payroll-month-shortcuts .progga-btn{padding-left:8px;padding-right:8px}
.payroll-workflow-summary{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.payroll-workflow-summary span{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800}.payroll-workflow-summary .draft{background:#fff3dd;color:#a86800}.payroll-workflow-summary .approved{background:#e9f3fb;color:#1466a0}.payroll-workflow-summary .paid{background:#e7f7ed;color:#16814b}
.payroll-item-filter-five{grid-template-columns:minmax(250px,2fr) minmax(165px,1fr) minmax(155px,1fr) minmax(155px,1fr) auto}.payroll-single-check-grid{grid-template-columns:repeat(4,minmax(0,1fr))}
@media(max-width:1199px){.payroll-item-filter-five{grid-template-columns:repeat(2,minmax(0,1fr))}.payroll-item-filter-five .hr-search{grid-column:span 2}}
@media(max-width:767px){.payroll-month-shortcuts,.payroll-single-check-grid,.payroll-item-filter-five{grid-template-columns:1fr}.payroll-item-filter-five .hr-search{grid-column:auto}}
</style>
