@extends('admin.master.master')
@section('title','Branch Inventory Comparison')
@section('body')
<main class="progga-content">
<div class="progga-page-header"><div><h1 class="progga-page-title">Branch-wise Inventory Summary</h1><p class="text-muted mb-0">Purchase value and operational counts are compared without incorrectly summing gram, milliliter and piece quantities together.</p></div><a href="{{ route('reports.inventory.index', request()->only('branch_id')) }}" class="progga-btn progga-btn-light">Report Home</a></div>
<div class="progga-card mb-4"><div class="p-3"><form method="GET" class="row g-2 align-items-end">@if($branches->count()>1 || $allBranches)<div class="col-md-3"><label class="progga-form-label">Branch</label><select name="branch_id" class="progga-form-control"><option value="all" @selected(request('branch_id')==='all' || $allBranches)>All Branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>@endif<div class="col-md-3"><label class="progga-form-label">From</label><input type="text" name="date_from" value="{{ request('date_from',$start->toDateString()) }}" class="progga-form-control progga-datepicker"></div><div class="col-md-3"><label class="progga-form-label">To</label><input type="text" name="date_to" value="{{ request('date_to',$end->toDateString()) }}" class="progga-form-control progga-datepicker"></div><div class="col-md-3"><button class="progga-btn progga-btn-primary">Apply</button></div></form></div></div>
<div class="progga-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Branch</th><th class="text-end">Received Purchases</th><th class="text-end">Purchase Value</th><th class="text-end">Consumed Orders</th><th class="text-end">Ledger Movements</th><th class="text-end">Transfers</th><th class="text-end">Wastage</th><th class="text-end">Low Stock</th><th class="text-end">Negative Stock</th><th class="text-end">Open Exceptions</th></tr></thead><tbody>@forelse($rows as $row)<tr><td><strong>{{ $row->branch_name }}</strong></td><td class="text-end">{{ number_format($row->purchase_count) }}</td><td class="text-end">৳{{ number_format((float)$row->purchase_value,2) }}</td><td class="text-end">{{ number_format($row->consumed_orders) }}</td><td class="text-end">{{ number_format($row->movement_count) }}</td><td class="text-end">{{ number_format($row->transfer_count) }}</td><td class="text-end">{{ number_format($row->wastage_count) }}</td><td class="text-end">{{ number_format($row->low_stock_rows) }}</td><td class="text-end {{ $row->negative_stock_rows ? 'text-danger fw-bold':'' }}">{{ number_format($row->negative_stock_rows) }}</td><td class="text-end">{{ number_format($row->open_exceptions) }}</td></tr>@empty<tr><td colspan="10" class="text-center text-muted py-5">No active branches in this scope.</td></tr>@endforelse</tbody></table></div></div>
</main>
@endsection
