@extends('admin.master.master')
@section('title','Daily Kitchen Reconciliation')
@section('body')
<main class="progga-content">
<div class="progga-page-header"><div><h1 class="progga-page-title">Daily Kitchen Reconciliation</h1><p class="text-muted mb-0">Opening + Main→Kitchen - Consumption - Wastage - Kitchen→Main +/- Adjustments = Closing.</p></div><a href="{{ route('reports.inventory.index', request()->only('branch_id')) }}" class="progga-btn progga-btn-light">Report Home</a></div>
<div class="progga-card mb-4"><div class="p-3"><form method="GET" class="row g-2 align-items-end">@if($branches->count()>1 || $allBranches)<div class="col-md-3"><label class="progga-form-label">Branch</label><select name="branch_id" class="progga-form-control"><option value="all" @selected(request('branch_id')==='all' || ($allBranches && !request()->has('branch_id')))>All Branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>@endif<div class="col-md-3"><label class="progga-form-label">From</label><input type="text" name="date_from" value="{{ request('date_from',$start->toDateString()) }}" class="progga-form-control progga-datepicker"></div><div class="col-md-3"><label class="progga-form-label">To</label><input type="text" name="date_to" value="{{ request('date_to',$end->toDateString()) }}" class="progga-form-control progga-datepicker"></div><div class="col-md-3"><button class="progga-btn progga-btn-primary">Apply</button></div></form></div></div>
<div class="alert alert-info">If <strong>Other Delta</strong> is non-zero, a non-standard ledger movement (for example an opening/reversal-type correction) affected Kitchen stock inside the selected period. The ledger closing still includes it.</div>
<div class="progga-card"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr>@if($allBranches)<th>Branch</th>@endif<th>Ingredient</th><th class="text-end">Opening</th><th class="text-end">Transfer In</th><th class="text-end">Consumption</th><th class="text-end">Wastage</th><th class="text-end">Return</th><th class="text-end">+ Adj</th><th class="text-end">- Adj</th><th class="text-end">Formula Closing</th><th class="text-end">Other Delta</th><th class="text-end">Ledger Closing</th></tr></thead><tbody>@forelse($rows as $row)<tr class="{{ $row->has_variance ? 'table-warning' : '' }}">@if($allBranches)<td>{{ $row->branch_name }}</td>@endif<td><strong>{{ $row->ingredient_name }}</strong><div class="text-muted small">{{ $row->location_name }}</div></td>@foreach(['opening','transfer_in','consumption','wastage','return_to_main','positive_adjustment','negative_adjustment','formula_closing','other_delta','ledger_closing'] as $field)<td class="text-end">{{ rtrim(rtrim((string)$row->{$field},'0'),'.') }} {{ $row->base_unit_symbol }}</td>@endforeach</tr>@empty<tr><td colspan="{{ $allBranches?12:11 }}" class="text-center text-muted py-5">No Kitchen balance rows found.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $rows->links() }}</div></div>
</main>
@endsection
