@extends('admin.master.master')
@section('title','Kitchen Request vs Issue')
@section('body')
<main class="progga-content">
<div class="progga-page-header"><div><h1 class="progga-page-title">Kitchen Request vs Required vs Issued</h1><p class="text-muted mb-0">Required quantity is preserved; partial issue remains auditable.</p></div><a href="{{ route('reports.inventory.index', request()->only('branch_id')) }}" class="progga-btn progga-btn-light">Report Home</a></div>
<div class="progga-card mb-4"><div class="p-3"><form method="GET" class="row g-2 align-items-end">@if($branches->count()>1 || $allBranches)<div class="col-md-3"><label class="progga-form-label">Branch</label><select name="branch_id" class="progga-form-control"><option value="all" @selected(request('branch_id')==='all' || ($allBranches && !request()->has('branch_id')))>All Branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>@endif<div class="col-md-3"><label class="progga-form-label">From</label><input type="text" name="date_from" value="{{ request('date_from',$start->toDateString()) }}" class="progga-form-control progga-datepicker"></div><div class="col-md-3"><label class="progga-form-label">To</label><input type="text" name="date_to" value="{{ request('date_to',$end->toDateString()) }}" class="progga-form-control progga-datepicker"></div><div class="col-md-3"><button class="progga-btn progga-btn-primary">Apply</button></div></form></div></div>
<div class="progga-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr>@if($allBranches)<th>Branch</th>@endif<th>Request</th><th>Date</th><th>Ingredient</th><th class="text-end">Required</th><th class="text-end">Approved</th><th class="text-end">Issued</th><th class="text-end">Remaining</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr>@if($allBranches)<td>{{ $row->branch_name }}</td>@endif<td><a href="{{ route('inventory.kitchen-requests.show',$row->kitchen_request_id) }}">{{ $row->request_no }}</a><div class="text-muted small">{{ $row->request_type }} / {{ $row->source_kind }}</div></td><td>{{ \Carbon\Carbon::parse($row->request_date)->format('d M Y') }}</td><td>{{ $row->ingredient_name }}</td><td class="text-end">{{ rtrim(rtrim((string)$row->required_base_qty,'0'),'.') }} {{ $row->base_unit_symbol }}</td><td class="text-end">{{ rtrim(rtrim((string)$row->approved_base_qty,'0'),'.') }} {{ $row->base_unit_symbol }}</td><td class="text-end">{{ rtrim(rtrim((string)$row->issued_base_qty,'0'),'.') }} {{ $row->base_unit_symbol }}</td><td class="text-end fw-semibold">{{ rtrim(rtrim((string)$row->shortage_base,'0'),'.') }} {{ $row->base_unit_symbol }}</td><td><span class="badge bg-secondary">{{ str_replace('_',' ',$row->status) }}</span></td></tr>@empty<tr><td colspan="{{ $allBranches?9:8 }}" class="text-center text-muted py-5">No kitchen request ingredient rows in this period.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $rows->links() }}</div></div>
</main>
@endsection
