@extends('admin.master.master')
@section('title', 'HR Dashboard — ' . $restaurantSettingName)
@section('css')
@include('admin.hr.shared.styles')
<style>
.hr-dashboard-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(330px,.75fr);gap:18px}.hr-quick-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hr-quick-link{display:flex;align-items:center;gap:10px;padding:13px;border:1px solid var(--progga-border-light);border-radius:12px;text-decoration:none;color:var(--progga-text);background:#fff}.hr-quick-link:hover{border-color:rgba(213,170,101,.65);color:var(--progga-primary);transform:translateY(-1px)}.hr-quick-link i{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;background:rgba(33,53,42,.08);color:var(--progga-primary)}.hr-roster-line{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 0;border-bottom:1px solid var(--progga-border-light)}.hr-roster-line:last-child{border-bottom:0}.leave-balance-item{padding:12px;border:1px solid var(--progga-border-light);border-radius:11px;background:#fafbfa}.leave-balance-name{font-size:11px;color:var(--progga-text-muted)}.leave-balance-value{font-size:20px;font-weight:900;color:var(--progga-primary);margin-top:2px}.hr-chart-wrap{height:300px}@media(max-width:991px){.hr-dashboard-grid{grid-template-columns:1fr}}@media(max-width:575px){.hr-quick-grid{grid-template-columns:1fr}.hr-chart-wrap{height:260px}}
</style>
@endsection
@section('body')
<main class="progga-content"><div class="hr-shell">
<div class="progga-page-header"><div><h1 class="progga-page-title">HR Dashboard</h1><div class="progga-breadcrumb"><a href="{{ route('home') }}" class="progga-breadcrumb-item">Dashboard</a><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">Human Resources</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item active">HR Dashboard</span></div></div><div class="hr-badge hr-badge-primary"><i class="bi bi-calendar3"></i> {{ now()->format('d F Y') }}</div></div>
<div class="hr-stat-grid">
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-people-fill"></i></div><div><div class="hr-stat-value">{{ $activeEmployees }}</div><div class="hr-stat-label">Active Employees</div></div></div>
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-person-check-fill"></i></div><div><div class="hr-stat-value">{{ $presentToday }}</div><div class="hr-stat-label">Present Today</div></div></div>
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-person-x-fill"></i></div><div><div class="hr-stat-value">{{ $absentToday }}</div><div class="hr-stat-label">Absent Today</div></div></div>
<div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-clock-history"></i></div><div><div class="hr-stat-value">{{ $lateToday }}</div><div class="hr-stat-label">Late Today</div></div></div>
</div>
<div class="hr-dashboard-grid">
<div>
<div class="hr-card mb-3"><div class="hr-card-header"><div><div class="hr-card-title">7-Day Attendance Overview</div><div class="hr-card-subtitle">Present, absent and late records from the last seven days.</div></div><a href="{{ route('hr.attendance.index') }}" class="progga-btn progga-btn-outline progga-btn-sm">Open Attendance</a></div><div class="hr-card-body"><div class="hr-chart-wrap"><canvas id="hrAttendanceChart"></canvas></div></div></div>
<div class="hr-card"><div class="hr-card-header"><div><div class="hr-card-title">Recent Leave Requests</div><div class="hr-card-subtitle">Latest leave activity requiring review or follow-up.</div></div><a href="{{ route('hr.leaves.index') }}" class="progga-btn progga-btn-outline progga-btn-sm">View All</a></div><div class="progga-table-wrapper" style="border:0;border-radius:0"><table class="progga-table"><thead><tr><th>Employee</th><th>Type</th><th>Period</th><th>Status</th></tr></thead><tbody>@forelse($recentLeaves as $leave)@php $badge=['pending'=>'warning','approved'=>'success','rejected'=>'danger','cancelled'=>'neutral'][$leave->status]??'neutral'; @endphp<tr><td><div class="hr-person-name">{{ $leave->employee?->name }}</div><div class="hr-person-meta">{{ $leave->employee?->employee_code }} · {{ $leave->employee?->department?->name }}</div></td><td>{{ $leave->leaveType?->name }}</td><td>{{ $leave->from_date->format('d-m-Y') }}<div class="hr-person-meta">to {{ $leave->to_date->format('d-m-Y') }}</div></td><td><span class="hr-badge hr-badge-{{ $badge }}">{{ $leave->status }}</span></td></tr>@empty<tr><td colspan="4"><div class="hr-empty"><i class="bi bi-calendar2-check"></i>No leave requests yet.</div></td></tr>@endforelse</tbody></table></div></div>
</div>
<div>
<div class="hr-card mb-3"><div class="hr-card-header"><div><div class="hr-card-title">Today at a Glance</div><div class="hr-card-subtitle">Operational exceptions and pending tasks.</div></div></div><div class="hr-card-body"><div class="row g-3"><div class="col-6"><div class="leave-balance-item"><div class="leave-balance-name">On Leave</div><div class="leave-balance-value">{{ $onLeaveToday }}</div></div></div><div class="col-6"><div class="leave-balance-item"><div class="leave-balance-name">Pending Leave</div><div class="leave-balance-value">{{ $pendingLeaves }}</div></div></div><div class="col-6"><div class="leave-balance-item"><div class="leave-balance-name">Scheduled</div><div class="leave-balance-value">{{ $scheduledToday }}</div></div></div><div class="col-6"><div class="leave-balance-item"><div class="leave-balance-name">Not Marked</div><div class="leave-balance-value">{{ $notMarkedToday }}</div></div></div></div></div></div>
<div class="hr-card mb-3"><div class="hr-card-header"><div><div class="hr-card-title">Quick Actions</div><div class="hr-card-subtitle">Common HR tasks for daily use.</div></div></div><div class="hr-card-body"><div class="hr-quick-grid"><a href="{{ route('hr.employees.index') }}" class="hr-quick-link"><i class="bi bi-person-plus"></i><div><strong>Employee</strong><div class="hr-muted">Add or update</div></div></a><a href="{{ route('hr.attendance.index') }}" class="hr-quick-link"><i class="bi bi-fingerprint"></i><div><strong>Attendance</strong><div class="hr-muted">Mark today</div></div></a><a href="{{ route('hr.shifts.index') }}" class="hr-quick-link"><i class="bi bi-calendar-week"></i><div><strong>Roster</strong><div class="hr-muted">Assign shifts</div></div></a></div></div></div>
<div class="hr-card"><div class="hr-card-header"><div><div class="hr-card-title">Today's Duty Roster</div><div class="hr-card-subtitle">First 10 roster entries for today.</div></div><a href="{{ route('hr.shifts.index') }}" class="progga-btn progga-btn-outline progga-btn-sm">Manage</a></div><div class="hr-card-body">@forelse($todayRoster as $roster)<div class="hr-roster-line"><div><div class="hr-person-name">{{ $roster->employee?->name }}</div><div class="hr-person-meta">{{ $roster->employee?->designation?->name }} · {{ $roster->employee?->department?->name }}</div></div><div class="text-end">@if($roster->status==='scheduled')<span class="hr-badge hr-badge-success">{{ $roster->shift?->name ?? 'No shift' }}</span><div class="hr-person-meta">{{ $roster->shift?->time_range }}</div>@elseif($roster->status==='leave')<span class="hr-badge hr-badge-info">Leave</span>@else<span class="hr-badge hr-badge-neutral">Off</span>@endif</div></div>@empty<div class="hr-empty"><i class="bi bi-calendar3"></i>No duty roster has been prepared for today.</div>@endforelse</div></div>
</div>
</div>
</div></main>
@endsection
@section('script')
<script>
document.addEventListener('DOMContentLoaded',function(){const ctx=document.getElementById('hrAttendanceChart');if(!ctx)return;new Chart(ctx,{type:'bar',data:{labels:@json($chartLabels),datasets:[{label:'Present',data:@json($chartPresent),borderWidth:1,borderRadius:6},{label:'Absent',data:@json($chartAbsent),borderWidth:1,borderRadius:6},{label:'Late',data:@json($chartLate),borderWidth:1,borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true,ticks:{precision:0}},x:{grid:{display:false}}}}});});
</script>
@endsection
