@extends('admin.master.master')
@section('title','Inventory Stock Ledger')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Stock Ledger</h1><p class="text-muted mb-0">Posted stock movements are immutable. Corrections are represented by new reversal or adjustment movements.</p></div><a href="{{ route('inventory.stock.index') }}" class="progga-btn progga-btn-secondary">Current Stock</a></div>
    <div class="progga-card mb-4 inventory-filter-card"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-md-3"><label class="progga-form-label">Movement Type</label><select name="movement_type" class="progga-form-control"><option value="">All movement types</option>@foreach($movementTypes as $type)<option value="{{ $type }}" @selected(request('movement_type')===$type)>{{ str_replace('_',' ',$type) }}</option>@endforeach</select></div><div class="col-md-3"><label class="progga-form-label">Location</label><select name="location_id" class="progga-form-control"><option value="">All locations</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)request('location_id')===(string)$location->id)>{{ $location->branch?->name }} - {{ $location->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="progga-form-label">Ingredient</label><select name="ingredient_id" class="progga-form-control"><option value="">All ingredients</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" @selected((string)request('ingredient_id')===(string)$ingredient->id)>{{ $ingredient->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="progga-form-label">From</label><input type="text" name="date_from" value="{{ request('date_from') }}" class="progga-form-control progga-datepicker"></div><div class="col-md-2"><label class="progga-form-label">To</label><input type="text" name="date_to" value="{{ request('date_to') }}" class="progga-form-control progga-datepicker"></div><div class="col-md-auto"><button class="progga-btn progga-btn-secondary">Apply Filter</button></div><div class="col-md-auto"><a class="progga-btn progga-btn-light" href="{{ route('inventory.ledger.index') }}">Clear</a></div></form></div></div>
    <div class="progga-card">
        <div class="progga-card-header inventory-list-toolbar"><div class="inventory-result-copy"><span class="fw-semibold">Ledger List</span><small class="text-muted" id="inventoryResultCount">{{ $movements->total() }} {{ $movements->total() === 1 ? 'record' : 'records' }}</small></div><div class="inventory-search-wrap"><i class="bi bi-search inventory-search-icon"></i><input type="search" id="inventorySearch" class="progga-form-control inventory-search-input" value="{{ request('search') }}" placeholder="Search movement, ingredient or reason..." autocomplete="off"><button type="button" id="inventorySearchClear" class="inventory-search-clear"><i class="bi bi-x-lg"></i></button></div></div>
        <div id="inventoryListContent"><div class="progga-table-wrapper" style="border:none;border-radius:0;"><table class="progga-table"><thead><tr><th style="width:70px;">SL</th><th>Movement</th><th>Branch</th><th>Type</th><th>Route</th><th>Items</th><th>Performed</th><th>Reason</th></tr></thead><tbody>
        @forelse($movements as $movement)<tr><td>{{ ($movements->firstItem() ?? 1)+$loop->index }}</td><td><strong>{{ $movement->movement_no }}</strong><br><small class="text-muted">{{ optional($movement->occurred_at)->format('d M Y, h:i A') }}</small></td><td>{{ $movement->branch?->name }}</td><td><span class="progga-badge progga-badge-info">{{ str_replace('_',' ',$movement->movement_type) }}</span></td><td>{{ $movement->sourceLocation?->name ?: '—' }} <i class="bi bi-arrow-right"></i> {{ $movement->destinationLocation?->name ?: '—' }}</td><td>@foreach($movement->items as $item)<div><strong>{{ $item->ingredient?->name }}</strong>: {{ rtrim(rtrim((string)$item->quantity_base,'0'),'.') }} {{ $item->ingredient?->baseUnit?->symbol }}</div>@endforeach</td><td>{{ $movement->performer?->name ?: 'System' }}</td><td>{{ $movement->reason ?: '—' }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">No posted stock movements found.</td></tr>@endforelse
        </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$movements,'label'=>'movements'])</div>
    </div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.ledger.index')])
@endsection
