@extends('admin.master.master')
@php $oldItems=old('items',[['ingredient_id'=>'','physical_qty_base'=>'']]); @endphp
@section('title','Physical Stock Count')
@section('body')
<main class="progga-content"><div class="progga-page-header"><div><h1 class="progga-page-title">Physical Stock Count</h1><p class="text-muted mb-0">Enter the actual physical quantity in each ingredient's base unit. System quantity is re-read under a database lock when posting.</p></div><a href="{{ route('inventory.adjustments.index') }}" class="progga-btn progga-btn-outline">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('inventory.adjustments.store') }}" onsubmit="return confirm('Post this physical stock adjustment?')">@csrf
<div class="progga-card mb-4"><div class="p-4"><div class="row g-3"><div class="col-md-4"><label class="progga-form-label">Stock Location</label><select id="adjustLocation" name="location_id" class="progga-form-control" onchange="refreshSystemQty()" required><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)old('location_id')===(string)$location->id)>{{ $location->name }} ({{ $location->type }})</option>@endforeach</select></div><div class="col-md-8"><label class="progga-form-label">Reason <span class="progga-required">*</span></label><input name="reason" value="{{ old('reason') }}" class="progga-form-control" placeholder="Physical count / variance reconciliation reason" required></div></div></div></div>
<div class="alert alert-warning"><strong>High-impact action:</strong> posting can create both positive and negative adjustment movements. It does not directly overwrite inventory balances.</div>
<div class="progga-card mb-4"><div class="progga-card-header d-flex justify-content-between"><div><strong>Count Rows</strong></div><button type="button" class="progga-btn progga-btn-secondary progga-btn-sm" onclick="addAdjustRow()">Add Ingredient</button></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ingredient</th><th style="width:220px">System Qty</th><th style="width:260px">Physical Qty (Base Unit)</th><th style="width:60px"></th></tr></thead><tbody id="adjustRows">@foreach($oldItems as $idx=>$row)<tr class="adjust-row"><td><select name="items[{{ $idx }}][ingredient_id]" class="progga-form-control adjust-ingredient" onchange="refreshSystemQty()" required><option value="">Select ingredient</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}" data-base="{{ $ingredient->baseUnit?->symbol }}" @selected((string)($row['ingredient_id']??'')===(string)$ingredient->id)>{{ $ingredient->name }} ({{ $ingredient->baseUnit?->symbol }})</option>@endforeach</select></td><td class="system-qty text-muted">—</td><td><div class="input-group"><input type="number" step="0.00000001" min="0" name="items[{{ $idx }}][physical_qty_base]" value="{{ $row['physical_qty_base']??'' }}" class="progga-form-control" required><span class="input-group-text base-symbol">base</span></div></td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeAdjustRow(this)"><i class="bi bi-trash"></i></button></td></tr>@endforeach</tbody></table></div></div><div class="d-flex justify-content-end"><button class="progga-btn progga-btn-primary">Post Physical Adjustment</button></div></form></main>
@endsection
@section('script')
<script>
const aIngredients={{ \Illuminate\Support\Js::from($ingredients->map(fn($i)=>['id'=>$i->id,'name'=>$i->name,'base'=>$i->baseUnit?->symbol])->values()) }};const aBalances=@json($systemBalances);let aIndex={{ count($oldItems) }};function ae(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}function ai(){return '<option value="">Select ingredient</option>'+aIngredients.map(i=>`<option value="${i.id}" data-base="${ae(i.base)}">${ae(i.name)} (${ae(i.base)})</option>`).join('');}
function addAdjustRow(){const tr=document.createElement('tr');tr.className='adjust-row';tr.innerHTML=`<td><select name="items[${aIndex}][ingredient_id]" class="progga-form-control adjust-ingredient" onchange="refreshSystemQty()" required>${ai()}</select></td><td class="system-qty text-muted">—</td><td><div class="input-group"><input type="number" step="0.00000001" min="0" name="items[${aIndex}][physical_qty_base]" class="progga-form-control" required><span class="input-group-text base-symbol">base</span></div></td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeAdjustRow(this)"><i class="bi bi-trash"></i></button></td>`;document.getElementById('adjustRows').appendChild(tr);aIndex++;refreshSystemQty();}function removeAdjustRow(b){if(document.querySelectorAll('.adjust-row').length<=1)return;b.closest('tr').remove();}
function refreshSystemQty(){const loc=document.getElementById('adjustLocation')?.value||'';document.querySelectorAll('.adjust-row').forEach(row=>{const s=row.querySelector('.adjust-ingredient'),id=s.value,o=s.options[s.selectedIndex],base=o?.dataset.base||'base',q=(aBalances[loc]&&aBalances[loc][id])?aBalances[loc][id]:'0.00000000';row.querySelector('.system-qty').textContent=id?`${String(q).replace(/\.?0+$/,'')} ${base}`:'—';row.querySelector('.base-symbol').textContent=base;});}document.addEventListener('DOMContentLoaded',refreshSystemQty);
</script>
@endsection
