<div class="modal fade progga-modal" id="salaryComponentModal" tabindex="-1">
    <div class="modal-dialog modal-lg"><div class="modal-content">
        <div class="modal-header"><h5 class="modal-title"><i class="bi bi-cash-stack me-2"></i><span class="modal-title-text">Add Salary Component</span></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
        <form id="salaryComponentForm" class="hr-ajax-form" data-entity="salary-components" data-tab="salary-components">
            @csrf<input type="hidden" name="id">
            <div class="modal-body"><div class="row g-3">
                <div class="col-md-6"><div class="progga-form-group"><label class="progga-form-label">Component Name <span class="progga-required">*</span></label><input type="text" name="name" class="progga-form-control" placeholder="e.g. House Rent" required></div></div>
                <div class="col-md-3"><div class="progga-form-group"><label class="progga-form-label">Code</label><input type="text" name="code" class="progga-form-control" placeholder="HR"></div></div>
                <div class="col-md-3"><div class="progga-form-group"><label class="progga-form-label">Type <span class="progga-required">*</span></label><select id="hrSalaryComponentType" name="type" class="progga-select hr-select2"><option value="earning">Earning</option><option value="deduction">Deduction</option></select></div></div>
                <div class="col-md-4"><div class="progga-form-group"><label class="progga-form-label">Calculation Type</label><select id="hrSalaryCalculationType" name="calculation_type" class="progga-select hr-select2"><option value="fixed">Fixed Amount</option><option value="percentage">Percentage</option><option value="manual">Manual Entry</option></select></div></div>
                <div class="col-md-4" id="salaryFixedFields"><div class="progga-form-group"><label class="progga-form-label">Default Amount</label><input type="number" step="0.01" name="default_amount" class="progga-form-control" min="0" value="0"></div></div>
                <div class="col-md-8" id="salaryPercentageFields" style="display:none;"><div class="row g-3"><div class="col-md-6"><div class="progga-form-group"><label class="progga-form-label">Default Percentage</label><div class="input-group"><input type="number" step="0.01" name="default_percentage" class="progga-form-control" min="0" value="0"><span class="input-group-text">%</span></div></div></div><div class="col-md-6"><div class="progga-form-group"><label class="progga-form-label">Percentage Of</label><select id="hrSalaryPercentageOf" name="percentage_of" class="progga-select hr-select2"><option value="basic_salary">Basic Salary</option><option value="gross_salary">Gross Salary</option></select></div></div></div></div>
                <div class="col-12"><div class="progga-form-group"><label class="progga-form-label">Description</label><textarea name="description" class="progga-form-control progga-form-textarea" rows="3"></textarea></div></div>
                <div class="col-md-3"><div class="progga-form-group"><label class="progga-form-label">Taxable</label><label class="progga-toggle" style="margin-top:8px;"><input type="checkbox" name="is_taxable" value="1" data-on="Taxable" data-off="Not Taxable"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">Not Taxable</span></label></div></div>
                <div class="col-md-3"><div class="progga-form-group"><label class="progga-form-label">Required</label><label class="progga-toggle" style="margin-top:8px;"><input type="checkbox" name="is_required" value="1" data-on="Required" data-off="Optional"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">Optional</span></label></div></div>
                <div class="col-md-3"><div class="progga-form-group"><label class="progga-form-label">Sort Order</label><input type="number" name="sort_order" class="progga-form-control" min="0" value="0"></div></div>
                <div class="col-md-3"><div class="progga-form-group"><label class="progga-form-label">Status</label><label class="progga-toggle" style="margin-top:8px;"><input type="checkbox" name="status" value="1" checked data-on="Active" data-off="Inactive"><span class="progga-toggle-track"><span class="progga-toggle-thumb"></span></span><span class="progga-toggle-label">Active</span></label></div></div>
            </div></div>
            <div class="modal-footer"><button type="button" class="progga-btn progga-btn-outline" data-bs-dismiss="modal">Cancel</button><button type="submit" class="progga-btn progga-btn-primary"><i class="bi bi-check-lg"></i> <span class="hr-submit-text">Save Component</span></button></div>
        </form>
    </div></div>
</div>
