@extends('admin.master.master')

@section('title', 'Payroll — ' . $run->month_label)

@section('css')
    @include('admin.hr.shared.styles')
@endsection

@section('body')
<main class="progga-content">
    <div class="hr-shell">
        <div class="progga-page-header">
            <div>
                <h1 class="progga-page-title">{{ $run->month_label }} Payroll</h1>
                <div class="progga-breadcrumb">
                    <a href="{{ route('home') }}" class="progga-breadcrumb-item">Dashboard</a>
                    <span class="progga-breadcrumb-sep">/</span>
                    <a href="{{ route('hr.payroll.index') }}" class="progga-breadcrumb-item">Payroll</a>
                    <span class="progga-breadcrumb-sep">/</span>
                    <span class="progga-breadcrumb-item active">{{ $run->payroll_code }}</span>
                </div>
            </div>
            <div class="d-flex gap-2 flex-wrap">
                @can('payroll-create')
                    <a href="{{ route('hr.payroll.single.create', ['month' => $run->payroll_month->format('Y-m')]) }}" class="progga-btn progga-btn-primary"><i class="bi bi-person-plus"></i> Add Employee Payroll</a>
                @endcan
                <a href="{{ route('hr.payroll.summary-pdf', $run) }}" target="_blank" class="progga-btn progga-btn-outline"><i class="bi bi-file-earmark-pdf"></i> Summary PDF</a>
                <a href="{{ route('hr.payroll.index') }}" class="progga-btn progga-btn-outline"><i class="bi bi-arrow-left"></i> Payroll List</a>
            </div>
        </div>

        @php
            $statusClass = match($run->status) { 'paid' => 'hr-badge-success', 'approved' => 'hr-badge-info', 'draft' => 'hr-badge-warning', default => 'hr-badge-neutral' };
        @endphp
        <div class="hr-card mb-3 payroll-run-hero">
            <div class="hr-card-body d-flex align-items-center justify-content-between gap-3 flex-wrap">
                <div>
                    <div class="d-flex align-items-center gap-2 flex-wrap">
                        <div class="hr-card-title">{{ $run->payroll_code }}</div>
                        <span class="hr-badge {{ $statusClass }}">{{ $run->status }}</span>
                    </div>
                    <div class="hr-card-subtitle mt-1">Period: {{ $run->period_start->format('d-m-Y') }} to {{ $run->period_end->format('d-m-Y') }} · Generated by {{ $run->generatedBy->name ?? 'System' }}</div>
                    <div class="payroll-workflow-summary mt-2">
                        <span class="draft"><i class="bi bi-pencil-square"></i> Draft {{ $draftCount }}</span>
                        <span class="approved"><i class="bi bi-patch-check"></i> Approved {{ $approvedCount }}</span>
                        <span class="paid"><i class="bi bi-cash-coin"></i> Paid {{ $paidCount }}</span>
                    </div>
                </div>
                <div class="d-flex gap-2 flex-wrap">
                    @if($draftCount > 0)
                        @can('payroll-create')
                            <form action="{{ route('hr.payroll.regenerate', $run) }}" method="POST" class="payroll-confirm-form" data-title="Recalculate draft employees?" data-text="Only Draft employee records will be regenerated. Approved and Paid records will remain unchanged.">
                                @csrf
                                <button class="progga-btn progga-btn-outline" type="submit"><i class="bi bi-arrow-repeat"></i> Recalculate Drafts</button>
                            </form>
                        @endcan
                        @can('payroll-approve')
                            <form action="{{ route('hr.payroll.approve', $run) }}" method="POST" class="payroll-confirm-form" data-title="Approve all remaining drafts?" data-text="All Draft employee payroll records will be approved. Already approved or paid employees remain unchanged.">
                                @csrf
                                <button class="progga-btn progga-btn-primary" type="submit"><i class="bi bi-patch-check"></i> Approve All Drafts</button>
                            </form>
                        @endcan
                    @elseif($approvedCount > 0)
                        @can('payroll-pay')
                            <button type="button" class="progga-btn progga-btn-primary" data-bs-toggle="modal" data-bs-target="#payAllModal"><i class="bi bi-cash-stack"></i> Pay All Approved</button>
                        @endcan
                    @endif
                </div>
            </div>
        </div>

        <div class="hr-stat-grid payroll-five-stats">
            <div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-people"></i></div><div><div class="hr-stat-value">{{ $run->total_employees }}</div><div class="hr-stat-label">Employees</div></div></div>
            <div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-plus-circle"></i></div><div><div class="hr-stat-value payroll-money">৳{{ number_format((float) $run->total_gross, 2) }}</div><div class="hr-stat-label">Gross Salary</div></div></div>
            <div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-dash-circle"></i></div><div><div class="hr-stat-value payroll-money">৳{{ number_format((float) $run->total_deduction, 2) }}</div><div class="hr-stat-label">Deduction</div></div></div>
            <div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-wallet2"></i></div><div><div class="hr-stat-value payroll-money">৳{{ number_format((float) $run->total_net, 2) }}</div><div class="hr-stat-label">Net Payable</div></div></div>
            <div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-check2-circle"></i></div><div><div class="hr-stat-value">{{ $paidCount }}/{{ $run->total_employees }}</div><div class="hr-stat-label">Employees Paid</div></div></div>
        </div>

        <div class="hr-card mb-3">
            <div class="hr-card-body">
                <div class="hr-filter-grid payroll-item-filter payroll-item-filter-five">
                    <div class="hr-search"><i class="bi bi-search"></i><input type="text" id="payrollItemSearch" class="progga-form-control" placeholder="Search employee name, code or department"></div>
                    <select id="payrollDepartment" class="hr-select2">
                        <option value="">All Departments</option>
                        @foreach($departments as $department)
                            <option value="{{ $department->name }}">{{ $department->name }}</option>
                        @endforeach
                    </select>
                    <select id="payrollItemStatus" class="hr-select2" data-search="false">
                        <option value="">All Workflow Status</option>
                        <option value="draft">Draft</option>
                        <option value="approved">Approved</option>
                        <option value="paid">Paid</option>
                    </select>
                    <select id="payrollPaymentStatus" class="hr-select2" data-search="false">
                        <option value="">All Payment Status</option>
                        <option value="unpaid">Unpaid</option>
                        <option value="paid">Paid</option>
                    </select>
                    <button type="button" class="progga-btn progga-btn-outline" id="payrollItemReset"><i class="bi bi-arrow-counterclockwise"></i> Reset</button>
                </div>
            </div>
        </div>

        <div class="hr-card" id="payrollItemsContainer">
            <div class="hr-empty"><div class="spinner-border spinner-border-sm"></div><div class="mt-2">Loading employee payroll...</div></div>
        </div>
    </div>
</main>

@if($draftCount === 0 && $approvedCount > 0)
<div class="modal fade hr-modal" id="payAllModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header"><h5 class="modal-title">Pay All Approved Employees</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
            <form action="{{ route('hr.payroll.pay-all', $run) }}" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="alert alert-warning">This records full net salary payment for {{ $approvedCount }} approved unpaid employee(s).</div>
                    <div class="mb-3"><label class="progga-form-label">Payment Date</label><input type="text" id="payAllDate" name="payment_date" class="progga-form-control" value="{{ now()->toDateString() }}" required></div>
                    <div class="mb-3"><label class="progga-form-label">Force Payment Method</label><select name="payment_method" class="hr-select2" data-search="false"><option value="">Use each employee's salary setup</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_banking">Mobile Banking</option></select></div>
                    <div class="mb-3"><label class="progga-form-label">Reference Number</label><input type="text" name="reference_number" class="progga-form-control"></div>
                    <div><label class="progga-form-label">Payment Note</label><textarea name="payment_notes" rows="3" class="progga-form-control"></textarea></div>
                </div>
                <div class="modal-footer"><button type="button" class="progga-btn progga-btn-outline" data-bs-dismiss="modal">Cancel</button><button type="submit" class="progga-btn progga-btn-primary"><i class="bi bi-check2-circle"></i> Confirm Approved Payments</button></div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

@section('script')
@include('admin.hr.shared.plugins')
<script>
$(function () {
    let currentPage = 1;
    let searchTimer;
    HrUi.initSelect2('.hr-select2');
    HrUi.initFlatpickr('#payAllDate');

    function loadItems(page) {
        currentPage = page || 1;
        const box = $('#payrollItemsContainer').addClass('hr-table-loading');
        $.get(@json(route('hr.payroll.items.table', $run)), {
            page: currentPage,
            search: $('#payrollItemSearch').val(),
            department: HrUi.selectValue('payrollDepartment'),
            item_status: HrUi.selectValue('payrollItemStatus'),
            payment_status: HrUi.selectValue('payrollPaymentStatus')
        }).done(function (html) {
            box.html(html);
        }).fail(function () {
            Swal.fire('Error', 'Failed to load employee payroll.', 'error');
        }).always(function () {
            box.removeClass('hr-table-loading');
        });
    }

    $('#payrollItemSearch').on('input', function () {
        clearTimeout(searchTimer);
        searchTimer = setTimeout(function () { loadItems(1); }, 350);
    });
    $('#payrollDepartment, #payrollItemStatus, #payrollPaymentStatus').on('change', function () { loadItems(1); });
    $('#payrollItemReset').on('click', function () {
        $('#payrollItemSearch').val('');
        HrUi.resetSelect('payrollDepartment');
        HrUi.resetSelect('payrollItemStatus');
        HrUi.resetSelect('payrollPaymentStatus');
        loadItems(1);
    });
    $(document).on('click', '#payrollItemsContainer .report-page-link:not(.disabled)', function (e) {
        e.preventDefault();
        const url = new URL(this.href);
        loadItems(url.searchParams.get('page') || 1);
    });

    $(document).on('submit', '.payroll-confirm-form, .payroll-item-approve-form', function (event) {
        event.preventDefault();
        const form = this;
        Swal.fire({ title: form.dataset.title, text: form.dataset.text, icon: 'warning', showCancelButton: true, confirmButtonText: 'Continue', confirmButtonColor: '#21352a' })
            .then(function (result) { if (result.isConfirmed) form.submit(); });
    });

    @if(session('success'))
        Swal.fire({ icon: 'success', title: 'Success', text: @json(session('success')), timer: 1900, showConfirmButton: false });
    @endif
    @if(session('error'))
        Swal.fire('Error', @json(session('error')), 'error');
    @endif

    loadItems(1);
});
</script>
@endsection
