<div class="modal fade hr-modal" id="leaveModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="leaveForm" enctype="multipart/form-data">@csrf
<div class="modal-header"><div><h5 class="modal-title" id="leaveModalTitle">New Leave Request</h5><div style="font-size:11px;opacity:.75">Weekly off days and holidays are excluded automatically.</div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="row g-3">
<div class="col-md-6"><label class="progga-form-label">Employee <span class="progga-required">*</span></label><select id="formLeaveEmployee" class="leave-form-select2"><option value="">Select Employee</option>@foreach($employees as $item)<option value="{{ $item->id }}">{{ $item->employee_code }} — {{ $item->name }}</option>@endforeach</select><div class="leave-error text-danger" data-error="employee_id"></div></div>
<div class="col-md-6"><label class="progga-form-label">Leave Type <span class="progga-required">*</span></label><select id="formLeaveType" class="leave-form-select2"><option value="">Select Leave Type</option>@foreach($leaveTypes as $item)<option value="{{ $item->id }}">{{ $item->name }} ({{ $item->days_per_year }} days)</option>@endforeach</select><div class="leave-error text-danger" data-error="leave_type_id"></div></div>
<div class="col-12"><div id="leaveBalancePanel" class="p-3" style="border:1px solid var(--progga-border-light);border-radius:12px;background:#fafbfa"><div class="hr-muted">Select an employee to view current leave balances.</div></div></div>
<div class="col-md-6"><label class="progga-form-label">From Date <span class="progga-required">*</span></label><input name="from_date" id="leaveFromDate" class="progga-form-control leave-form-date"><div class="leave-error text-danger" data-error="from_date"></div></div>
<div class="col-md-6"><label class="progga-form-label">To Date <span class="progga-required">*</span></label><input name="to_date" id="leaveToDate" class="progga-form-control leave-form-date"><div class="leave-error text-danger" data-error="to_date"></div></div>
<div class="col-12"><div class="p-2" style="border-radius:9px;background:rgba(33,53,42,.06);font-size:12px"><i class="bi bi-calculator me-1"></i> <span id="leaveDayPreview">0 working day</span></div></div>
<div class="col-12"><label class="progga-form-label">Reason <span class="progga-required">*</span></label><textarea name="reason" id="leaveReason" class="progga-form-control" rows="4"></textarea><div class="leave-error text-danger" data-error="reason"></div></div>
<div class="col-12"><label class="progga-form-label">Supporting Document</label><input type="file" name="attachment" class="progga-form-control" accept=".pdf,.jpg,.jpeg,.png"><div class="hr-muted mt-1">PDF or image, maximum 2 MB.</div><div class="leave-error text-danger" data-error="attachment"></div></div>
</div></div>
<div class="modal-footer"><button type="button" class="progga-btn progga-btn-outline" data-bs-dismiss="modal">Cancel</button><button type="submit" class="progga-btn progga-btn-primary" id="leaveSaveBtn"><i class="bi bi-check-lg"></i> <span id="leaveSaveText">Submit Request</span></button></div>
</form></div></div></div>
