@extends('admin.master.master')
@section('title','Stock Transfers')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Stock Transfers & Returns</h1><p class="text-muted mb-0">Main → Kitchen issues and Kitchen → Main unused-stock returns are physical location movements, not consumption.</p></div><div class="d-flex gap-2">@can('inventory-return-post')<a href="{{ route('inventory.transfers.return.create') }}" class="progga-btn progga-btn-secondary"><i class="bi bi-arrow-return-left"></i> Kitchen Return</a>@endcan @can('inventory-transfer-post')<a href="{{ route('inventory.transfers.create') }}" class="progga-btn progga-btn-primary"><i class="bi bi-arrow-left-right"></i> Direct Transfer</a>@endcan</div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="progga-card mb-4 inventory-filter-card"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-md-4"><label class="progga-form-label">Direction</label><select name="direction" class="progga-form-control"><option value="">All directions</option><option value="MAIN_TO_KITCHEN" @selected(request('direction')==='MAIN_TO_KITCHEN')>Main → Kitchen</option><option value="KITCHEN_TO_MAIN" @selected(request('direction')==='KITCHEN_TO_MAIN')>Kitchen → Main</option></select></div><div class="col-md-auto"><button class="progga-btn progga-btn-secondary">Apply Filter</button></div><div class="col-md-auto"><a href="{{ route('inventory.transfers.index') }}" class="progga-btn progga-btn-light">Clear</a></div></form></div></div>
    <div class="progga-card">
        <div class="progga-card-header inventory-list-toolbar"><div class="inventory-result-copy"><span class="fw-semibold">Transfer List</span><small class="text-muted" id="inventoryResultCount">{{ $transfers->total() }} {{ $transfers->total() === 1 ? 'record' : 'records' }}</small></div><div class="inventory-search-wrap"><i class="bi bi-search inventory-search-icon"></i><input type="search" id="inventorySearch" class="progga-form-control inventory-search-input" value="{{ request('search') }}" placeholder="Search transfer or request number..." autocomplete="off"><button type="button" id="inventorySearchClear" class="inventory-search-clear"><i class="bi bi-x-lg"></i></button></div></div>
        <div id="inventoryListContent"><div class="progga-table-wrapper" style="border:none;border-radius:0;"><table class="progga-table"><thead><tr><th style="width:70px;">SL</th>@if(($allBranchesSelected ?? false))<th>Branch</th>@endif<th>Transfer</th><th>Direction</th><th>Kitchen Request</th><th>Items</th><th>Posted</th><th>Posted By</th><th style="width:70px;">Actions</th></tr></thead><tbody>
        @forelse($transfers as $transfer)<tr><td>{{ ($transfers->firstItem() ?? 1)+$loop->index }}</td>@if(($allBranchesSelected ?? false))<td>{{ $transfer->branch?->name }}</td>@endif<td><a href="{{ route('inventory.transfers.show',$transfer) }}"><strong>{{ $transfer->transfer_no }}</strong></a></td><td><span class="progga-badge progga-badge-info">{{ str_replace('_TO_',' → ',$transfer->direction) }}</span></td><td>@if($transfer->kitchenRequest)<a href="{{ route('inventory.kitchen-requests.show',$transfer->kitchenRequest) }}">{{ $transfer->kitchenRequest->request_no }}</a>@else<span class="text-muted">Direct</span>@endif</td><td>{{ $transfer->items_count }}</td><td>{{ $transfer->posted_at?->format('d M Y h:i A') }}</td><td>{{ $transfer->poster?->name ?: '—' }}</td><td><div class="progga-table-actions"><a href="{{ route('inventory.transfers.show',$transfer) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="View"><i class="bi bi-eye"></i></a></div></td></tr>@empty<tr><td colspan="{{ ($allBranchesSelected ?? false) ? 9 : 8 }}" class="text-center text-muted py-5">No stock transfers found.</td></tr>@endforelse
        </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$transfers,'label'=>'transfers'])</div>
    </div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.transfers.index')])
@endsection
