@extends('admin.master.master')
@section('title','Stock Transfer '.$transfer->transfer_no)
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">{{ $transfer->transfer_no }}</h1><p class="text-muted mb-0">{{ $transfer->branch?->name }} · {{ str_replace('_TO_',' → ',$transfer->direction) }}</p></div><div class="d-flex gap-2"><a href="{{ route('inventory.transfers.index') }}" class="progga-btn progga-btn-outline">Back</a>@if($transfer->kitchenRequest)<a href="{{ route('inventory.kitchen-requests.show',$transfer->kitchenRequest) }}" class="progga-btn progga-btn-secondary">Kitchen Request</a>@endif @if($transfer->direction===\App\Models\StockTransfer::DIRECTION_MAIN_TO_KITCHEN) @can('inventory-return-post')<a href="{{ route('inventory.transfers.return.create',['transfer_id'=>$transfer->id]) }}" class="progga-btn progga-btn-primary">Return Unused Stock</a>@endcan @endif</div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="alert alert-success"><strong>POSTED</strong> — this transfer is immutable. Source and destination balances were changed atomically through ledger movement <strong>{{ $transfer->postedMovement?->movement_no }}</strong>. @if($transfer->originalTransfer) Return reference: <strong>{{ $transfer->originalTransfer->transfer_no }}</strong>. @endif</div>
    <div class="progga-card mb-4"><div class="p-4"><div class="row g-3"><div class="col-md-3"><small class="text-muted">Source</small><div>{{ $transfer->sourceLocation?->name }}</div></div><div class="col-md-3"><small class="text-muted">Destination</small><div>{{ $transfer->destinationLocation?->name }}</div></div><div class="col-md-3"><small class="text-muted">Posted At</small><div>{{ $transfer->posted_at?->format('d M Y h:i A') }}</div></div><div class="col-md-3"><small class="text-muted">Posted By</small><div>{{ $transfer->poster?->name ?: '—' }}</div></div><div class="col-12"><small class="text-muted">Notes</small><div>{{ $transfer->notes ?: '—' }}</div></div></div></div></div>
    <div class="progga-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Ingredient</th><th>Input Quantity</th><th>Conversion Snapshot</th><th>Base Quantity</th><th>{{ $transfer->sourceLocation?->name }} Before → After</th><th>{{ $transfer->destinationLocation?->name }} Before → After</th></tr></thead><tbody>
    @foreach($transfer->items as $item)
        @php $movementItem=$transfer->postedMovement?->items?->firstWhere('ingredient_id',$item->ingredient_id); @endphp
        <tr><td><strong>{{ $item->ingredient?->name }}</strong></td><td>{{ rtrim(rtrim((string)$item->quantity,'0'),'.') }} {{ $item->packageConversion?->label ?: $item->unit?->symbol }}</td><td>× {{ rtrim(rtrim((string)$item->conversion_factor_snapshot,'0'),'.') }}</td><td class="fw-semibold">{{ rtrim(rtrim((string)$item->base_quantity,'0'),'.') }} {{ $item->ingredient?->baseUnit?->symbol }}</td><td>{{ rtrim(rtrim((string)($movementItem?->source_before ?? '0'),'0'),'.') }} → {{ rtrim(rtrim((string)($movementItem?->source_after ?? '0'),'0'),'.') }}</td><td>{{ rtrim(rtrim((string)($movementItem?->destination_before ?? '0'),'0'),'.') }} → {{ rtrim(rtrim((string)($movementItem?->destination_after ?? '0'),'0'),'.') }}</td></tr>
    @endforeach
    </tbody></table></div></div>
</main>
@endsection
